### ISSUE TITLE
Uploader battery show constant value

### ISSUE THREAD

**Issue by jweismann** [nightscout/cgm-remote-monitor#1275]
FYI: After upgrading to the rest api the uploader battery box showed a constant value. I had to delete the devicestatus collection on mongolab to fix the problem. 

Thanks, jacob

**Comment by jasoncalabrese** [comment]
This is due to the date format not matching between the Rest API and Direct Mongo, the solution is to clear your devicestatus collection.  You can do that from Mongolab or if you're testing the 0.8.2 beta from the new admin tools

http://www.nightscout.info/wiki/faqs-2/mongo/battery-information-not-updating-on-website

<img width="1260" alt="screen shot 2015-10-26 at 3 38 37 pm" src="https://cloud.githubusercontent.com/assets/751143/10744506/ab19e122-7bf7-11e5-9758-eb80f961a9a7.png">
