### ISSUE TITLE
Error Trapping on MONGO Variable

### ISSUE THREAD

**Issue by jwedding** [nightscout/cgm-remote-monitor#144]
Remote monitor should validate the MONGO variable before attempting to use it. As it stands now, we get a 504 error if we are lucky, and a blank screen in many browsers.
##

**Comment by oskarpearson** [comment]
I'm going through old issue reports. This appears to have been resolved. Please let me know if I've missed something. Thanks!

If I don't supply MONGO_CONNECTION with 0.9.3-dev-20161212b I get this error on the console:
> mongo err [Error: MongoDB connection string is missing]

If I supply a bogus value, I get a message like this:
>mongo err [Error: invalid schema, expected mongodb]

On the web UI I get a similar error message, rather than the blank screen referred to in the issue.

>Nightscout - Boot Error
>
>Unable to connect to Mongo
>{"stack":"Error: MongoDB connection string is missing
