### ISSUE TITLE
Pushover CAGE SAGE not sending alerts

### ISSUE THREAD

**Issue by fallon225** [nightscout/cgm-remote-monitor#1597]
CAGE and SAGE are not sending alerts through Pushover.

**Comment by oamyoamy** [comment]
Same here.

**Comment by oamyoamy** [comment]
I am still not seeing these come through on the site or in Pushover.

**Comment by jasoncalabrese** [comment]
Should be working with dev now

**Comment by fallon225** [comment]
We are now getting alerts, but not persistent. We got cannula age 68 hours at 10am and 10:16am (white notification), cannula age 70 hours at 12pm (red alert), cannula age 72 hours overdue at 2pm (red alert), and that's it. We did not reset it, but have not received an alert since the 2pm. This has happened a few times now. How can we set it up so that it continues to alert? It does not give an option to clear notification in pushover like high or low alarms do. (Same with CAGE and SAGE)

**Comment by jasoncalabrese** [comment]
The way it's setup, alarms will only happen once, otherwise you'd get
non-stop alarms till the site was changed.

Need some kind of smarter snoozing, but not sure how it would work.  We
might have to store the ack in mongo.

We are now getting alerts, but not persistent. We got cannula age 68 hours
at 10am and 10:16am (white notification), cannula age 70 hours at 12pm (red
alert), cannula age 72 hours overdue at 2pm (red alert), and that's it. We
did not reset it, but have not received an alert since the 2pm. This has
happened a few times now. How can we set it up so that it continues to
alert? It does not give an option to clear notification in pushover like
high or low alarms do. (Same with CAGE and SAGE)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/nightscout/cgm-remote-monitor/issues/1597#issuecomment-225717186>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAt2J14jW66IM-usVNaSmlBqX566bx_lks5qLc4-gaJpZM4IDf4V>
.

**Comment by inform880** [comment]
Yeah, we need persistent alarms (at my house anyway). Once it's cleared, it's forgotten about. I'd like to see the snoozing just like the high alarms, with a 60 minute default time.

**Comment by fallon225** [comment]
Yeah, we need persistent alarms (at my house anyway). Once it's cleared, it's forgotten about. I'd like to see the snoozing just like the high alarms, with a 60 minute default time.

**Comment by whoiswes** [comment]
+1 for snoozing of CAGE, IAGE, and SAGE alarms, we have the EXACT same problem @fallon225
