### ISSUE TITLE
New Care Portal Treatment Types - Temp Basal Start and Stop

### ISSUE THREAD

**Issue by rokheart** [nightscout/cgm-remote-monitor#175]
I am very new to this group and am just getting my development environment setup and running, but I wanted to request (and prototype) a very minor addition to the care portal functionality.  I was not sure exactly what changes would be required so I waited until it was running on my machine before posting here.

To maintain my son's BG using an Omnipod, we use a combination of Bolus' and Temp Basal's, so I wanted to discuss the supporting the tracking of the Temp Basal's in addition to the bolus entries already in the care portal.

So, I got the code and created a branch wip/basal, and figured out that the change was VERY simple (with the assumption that the Insulin Given would be reused and no unique field for the time period).

I tested the setup with MongoLab database and both Azure and my local Node.js and the entries came across as expected.  

Anyway, I wanted to throw this up to you all for discussion.  Also, I do not know how to show/point you to my branch (or if you can see it automatically).  

Let me know your thoughts.

Michael McArthur
##

**Comment by StuArnold** [comment]
Having being using BWP in Dev and adding the TBR in Notes I can see the benefit of just recording more clearly when a TBR is applied than using the notes section. I understand the maths would be difficult to include in any calculations as the TBR may be cancelled part way through so I am not asking for that just a specific recording type to make the TBR more visible on the chart.

What would also be nice though is a Basal offset variable in Azure so that any TBR can be entered as the user does in the pump . It would also make the BWP clearer as the BWP calculation would be the (current calculation - the Basal offset) 

e.g. For a Vibe I would set 100 as the factor in Azure as normal basal is 0%
When I entered -20% as my TBR in the Careportal it would be stored as -20% +100 = 80%
 the BWP calculation would be the 80%-100 = -20% for display

If the normal basal is 100% then the factor would be 0
When I entered 80% as my TBR in the Careportal it would be stored as 80%+0 = 80%
 the BWP calculation would be the 80%- 0 = 80% for display

Hope I am making some kind of sense.

Not sure the factor is the right way round i,e. should Vibe be 0 and others -100 because if the TBR calculation is added it would presumably be a series of small negative or positive boluses so using 0% as the centre point may be easier in the longer term. 

Thanks again for all the brilliant work. I am really enjoying the BWP which is why I am asking. I am sure the last few days our control has been significantly better as the math has been done for us and we can focus on making a decision not working out the calculations.

**Comment by jasoncalabrese** [comment]
Like all the issues we've had with units I'm thinking we should store the values in the format they are entered in the pumps.  So for Ping/Vibe storing +/- x% (+50%, -20%) and for Medtronic storing an absolute percent (150%, 80%).  Then for display/calculations we can convert.  There's also the issue of rounding based on the pumps step motor.

To have temp basals adjust net IOB the easy thing to do would be to create a bunch on micro bolus treatments, and adjust how they are displayed on the chart.  What ever we do here will be very similar to combo/extended boluses.

I'm sure @sulkaharo has more thoughts on this...

**Comment by StuArnold** [comment]
Has not thought about the rounding - also I think maximum tbr varies pump to pump so I think Vibe can do +200% but would need to double check that and I assume that affects what the BWP will recommend.

In terms of display I would have thought marking a start and finish was probably easiest and use the microbolus only in calculations. Otherwise the chart would be busy. Perhaps have a pair of linked dots at the bottom of the chart?

Having been using the BWP for a few days with values that feel close - it does feel that  this is the next missing piece knowing that COB is a big challenge.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3

**Comment by StuArnold** [comment]
Hi Thanks again. Adding TBR is now incorporated so agree this issue is resolved.
Think there are two related issues;
1. Inclusion of TBR into IOB calculation.
2. Need to catch up with Autotune because the last time I tried it (4 months ago) I struggled because we use %age TBR fields and it required absolute values - not sure my brain is able to work out +60% of 0.85 at 2 am in the morning

I was just updating after I saw your tweet so will check if they are still relevant, that there is not an existing ticket and only raise a ticket if necessary.
Thanks
