### ISSUE TITLE
Time formats and structure differ between Mongo Collections

### ISSUE THREAD

**Issue by someoneAnyone** [nightscout/cgm-remote-monitor#208]
Hi, I'm new to the project and just starting to unwrap the data but I noticed that time is recorded in a few different ways. It would be ideal if it was standardized and documented (which format etc...). Hope this helps! I'm a big fan of this project.

Below is what I've observed:

CGM
{
...
    "date": 1414370037000,
    "dateString": "10/26/2014 08:33:57 PM",
...
}
devicestatus
{
... 
 "created_at": {
       "$date": "2014-10-22T23:44:58.135Z"
}
...
}
treatment
{
...
    "created_at": "2014-10-23T01:55:13.636Z",
...
}
##

**Comment by jareware** [comment]
I was about to open an issue on the `date` field being missing from the Treatments model, but... do you think the milliseconds-UTC `date` field would be removed as well? If there was a unified property for this, what would it be?

Milliseconds is nice because it's immediately compatible with `new Date()`, but then again I admit full ISO-8601 strings are easier on the eyes when debugging.

**Comment by bewest** [comment]
It's important to get everything converted to ISO8601.

Which uploader produced your cgm record, we should get it patched/updated to latest so they match.
All mine look like this:

CGM
```
    "date": 1449434107000,
    "dateString": "2015-12-06T20:35:07+00:00",

```

Treatments:
```
    "created_at": "2015-12-06T12:02:25-08:00",

```

Note, with ISO8601, it doesn't matter what the timezone is, so long as it's correctly encoded. :smile_cat:

**Comment by jareware** [comment]
@bewest do you think there should still be the number of milliseconds too, though? Or just a single field? If so, should that be called the same across all object types?
