### ISSUE TITLE
Links on front page appear to be nameless to screen readers

### ISSUE THREAD

**Issue by gcastellanos** [nightscout/cgm-remote-monitor#2395]
When using Night Scout with a screen reader, the links on the front landing page do not have any description as to what they do. simply hear"link". This isnt very helpful to know what each link does.
If you add the aria-label via a script that would work, or if you edit the html directly.  then Screen readers and other assistive technologies could use that information. Would be happy to work with someone on a fix, to liven up the sight from an accessibility / screen reader point of view.

**Comment by jasoncalabrese** [comment]
Seems like adding to the html directly would be easiest, do you want to send a PR for that?

**Comment by sulkaharo** [comment]
Hey also if you have the time, I'd love to hear how you'd expect Nightscout to behave when used voice-assisted or with voice only. My understanding is we can add a lot of hinting into the site as to what the voice behavior should be, but we don't have the expertise to know what the expected behavior would be for someone who frequently uses voice assist technology.

**Comment by gcastellanos** [comment]
@sulkaharo I'd love to answer your questions and give you some feedback. lets what is the best way to facilitate that? @jasoncalabrese let me know if i need to change anything... i'm still sort of new.
