### ISSUE TITLE
Feature Request: Bolus Wizard Rounding to 0.05 units versus 0.01

### ISSUE THREAD

**Issue by Deweyoxberg** [nightscout/cgm-remote-monitor#2711]
As of 0.9.0-beta3 the Bolus Wizard calculates rounding to the nearest 0.01 units; can this be changed to nearest 0.05 units instead?

**Comment by Pogman** [comment]
This should be extended to all rounding as an option in the user web settings.

For users of Medtronic pumps the rounding is 0.005. If I use the Temp Basal and set it to -80% it will produce a different value then what is used by the pump due to rounding.

PUMP_ROUNDING (<value>) or just a general ROUNDING (<value>) where <value> is something like 0.01 or 0.005 etc would be ideal.

**Comment by YYCMichael** [comment]
Any news on this request?

Tried these local edits in /lib/client/boluscalc.js : 

Line 460: record.insulin = roundTo(total, 0.05);  >>> to 0.1
and
Line 304: $('#bc_rouding').text(record.roundingcorrection.toFixed(2));
Line 305: $('#bc_insulintotal').text(record.insulin.toFixed(2));
to
$('#bc_rouding').text(record.roundingcorrection.toFixed(1));
$('#bc_insulintotal').text(record.insulin.toFixed(1));

Still rounding to nearest 0.05 units.
