### ISSUE TITLE
Need bigger font in PILL

### ISSUE THREAD

**Issue by JoseeT1Bionique** [nightscout/cgm-remote-monitor#3024]
Hi,

Would it be possible that the PILL opens in a bigger format, hence use bigger typo?  
I use web and android phone, the phone pill is especially hard to read sometimes.

Thank you for all done and all coming :)

**Comment by Kdisimone** [comment]
@JoseeT1Bionique you can customize your font size using the values in this page.

https://github.com/nightscout/cgm-remote-monitor/blob/master/static/css/main.css

for further detail about how to do that...you can also watch this video that shows a similar example using custom font color changes in that file.  https://youtu.be/fHIe16COGhE

I'd recommend closing this issue since it isn't really for overall users, but really more of a request for how to customize your site.  Check out the info above and you should be able to modify how you'd like.  Thanks.

**Comment by PieterGit** [comment]
@JoseeT1Bionique : can you give a followup on @Kdisimone comment. There have been some changes to the CSS since november 2017 so I don't know if this issue is still relevant for you.
Closing this issue for now. Feel free to reopen it, if you have more specific details / screenshots about what you want to improve.

**Comment by JoseeT1Bionique** [comment]
Hello, 

Thank you for the info, I will look into it. Closing it is fine.

Have a great day. 

Josée
