### ISSUE TITLE
Wrong IOB Calculation for MDI users

### ISSUE THREAD

**Issue by mdomox** [nightscout/cgm-remote-monitor#3268]
ΙΟΒ does not calculate correct value when changing treatment profiles with different insulin age value. This occurs in every browser and platform.

1. Create a treatment profile with insulage age 6 hours (profile Humulin)
2. Create a treatment profile with insulin age 2 hours (profile Novorapid)
3. Use profile Humulin. Insert bolus value 
4. After 2 hours change profile to Profile Novorapid. 
5. Nightscout  will calculate IOB, as if the insulin age was 2 hours from the beginning.... 

![screenshot_7](https://user-images.githubusercontent.com/2255012/35197950-2b445080-fef0-11e7-93c1-57e2ab03ce98.png)

![screenshot_8](https://user-images.githubusercontent.com/2255012/35197949-2b1eecdc-fef0-11e7-9262-e6ec7d46c1c6.png)

**Comment by PieterGit** [comment]
@mdomox Some questions to get the issue clear:
- Am I right that you're not using an APS system (openaps/oref0/loop/AndroidAPS) and only use Nightscout for viewing your viewing your CGM. 
- What pump do you use, and do you sync your pump with Nightscout, or only add manual treatments in Nightscout

Most people use IOB calculation from the APS. Nightscout IOB and BWP use simpler algorithms than those APS'es.

**Comment by mdomox** [comment]
@PieterGit Thank you much for your response. I use Nightscout for viewing CMG data (Freestlye Libre), manually inserting carbs and insulin doses. Not using a pump, but I find the bolus calculator very helpful.I also use it to view IOB, COB ,share date to the doctor and remotely monitor my kid's glucose levels  (fyi, till recently I was also using the GoogleHome - API.AI integration which was broken after the last release)

Is there a way to use an APS system you mentioned since I do not use a pump?

**Comment by MilosKozak** [comment]
AndroidAPS and virtual pump

**Comment by mdomox** [comment]
@MilosKozak , AndroidAPS has to be installed on the same smartphone as xDrip/Glimp?

**Comment by PieterGit** [comment]
@mdomox Can you give an update if this issue is still relevant? Since AndroidAPS runs on Android I would install it on the same phone as Xdrip Plus. Please tell me if you have additional questions. Removing 0.11 milestone, since I'm thinking this is not a bug, but a question of how to use Nightscout.

**Comment by mdomox** [comment]
> @mdomox Can you give an update if this issue is still relevant? Since AndroidAPS runs on Android I would install it on the same phone as Xdrip Plus. Please tell me if you have additional questions. Removing 0.11 milestone, since I'm thinking this is not a bug, but a question of how to use Nightscout.

@PieterGit Of course this is still relevant. Using AndroipAPS does not solve it. It has to do with the fact that IOB is calculated using insulin age as a globall system/profile attribute not per treatment (in cases where different insulin types are used). Each treatment should have the insulin age curve as an attribute, calculate the decay of the insulin of the treatment and determine the treatment IOB and the overall IOB to be calculated by adding all treatment IOBs that are >0 .

**Comment by PieterGit** [comment]
@mdomox The IOB calculation within Nightscout hasn't been touched for 3-4 years, see 
https://github.com/nightscout/cgm-remote-monitor/blame/7c272ec67a7795e0f4edf7ff9abdfac1bd1308a0/lib/plugins/iob.js#L189-L207

All APS'es use much better algorithms for calculating IOB now (including FIASP), see https://github.com/openaps/oref0/issues/544

So I think there are 3 options for Nightscout IOB:
1.  We remove the IOB calculation from Nightscout, and see it as an APS responsibility. Perhaps AndroidAPS with Virtual Pump has some kind of method that you can use the IOB calculation even without a pump. This will also solve wrong IOB results for OpenAPS users, see
https://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Rig-NS-communications-troubleshooting.html?highlight=iob%20pill#nightscout-info-incorrect

2. We upgrade and fix the IOB calculation withing Nightscout. In 0.11 to fix this issue, and in Nightscout 0.12  to include FIASP and to use the modern algorithms.

3. We remove the IOB pill altogether, and IOB is only showed with the OpenAPS / APS pill. Non pump users should use a VirtualPump with an APS to see IOB within Nightscout.

I think I would prefer option 1 or 2. In both cases the change should be created in the next 2 weeks (including documentation), so that we can test it for all cases and still release Nightscout 0.11 in December.

@jasoncalabrese @scottleibrand @sulkaharo @mddub @MilosKozak @warstar2187 Thoughts?

**Comment by scottleibrand** [comment]
Options 1 or 2 work for me. I’d strongly vote against 3: the IOB pill is far easier to read than having to mouse-over or tap the OpenAPS pill to see IOB. 

Scott

**Comment by mdomox** [comment]
@PieterGit 
OpensAPS does IOB calculations in Virtual Pump mode, but also handles decay curves and DIA in a global manner (global attribute), not per treatment. The issue is that, when not using a pump, different insulin types with different insulin decay curves and DIA can be used from treatment to treatment (ultra fast, fast, medium, long). When using a pump, one type of insulin is administered though.

Support of no pump users is minimum in AndroidAPS.

I raised this issue in OpenAPS community, and the impression I got is that OpenAPS is focused on pump users who they use one type of insulin. Not great interest on supporting non pump users. Maybe I am wrong.

**Comment by PieterGit** [comment]
@mdomox A bit off topic: I think the #WeAreNotWaiting focuses on using technology for all people with diabetes. On the other hand I think most Nightscout users use a pump instead of MDI. The last releases we found out that we have quite some parts of the code that are not well known and not always maintained (having code that is used by a lot of users and is not maintained is not good). Examples: Azure hosting, `svgdata` and share2nightscoutbridge. So it's not that we are not interesed in no pump  / MDI users, but I think we currently have less MDI users that are contributing to Nightscout.  If you can change that by doing a lot of contributions and bringing more MDI users, please do 😄 .  

On Topic: So I think we can agree on option 2 route. The removal options in 1 and 3 are mainly based on "better to remove stuff that has errors and is not well maintained in order to  prevent wrong information". IOB and COB calculations should always be implemented correct and be maintained, from a safety perspective.

For 0.11 we need some small fixes. The new alogrithms (and FIASP) are implemented in the APS'es and should be implemented in either Nightscout or some implementation of a Virtual APS for MDI users. It's up to the contributors to choose whether they will implement it as a plugin/module for Nightscout or as and extension of AndroidAPS.

**Comment by LongboatAline** [comment]
I think this may be one of the cases where the data model would profit from adding the type of insulin curve to use for the decay of the insulin in question.
Not only would it allow to calculate a reasonable approximation of IOB (and Acting Insulin) for users of MDI, it would also allow to cover uses of different Insulins for pump users as well.

Incomplete list of use cases where more than one insulin is used:
* MDI (well, obviously)
* Pump users (and loopers) might want to use an additional basal insulin when going untethered, (sauna, swimming, other situations where they'd prefer a long acting insulin to a manual dose every 2-3 hours).
* Pump users using a slower insulin in their pump, such as Insuman Infusat, might use an additional fast-acting insulin to speed up corrections, or to cover meals with a high glycemic index.
* MDI users might use more than 2 insulins, for example an NPH insulin to cover Fat/Protein based meals. 
* Either might occasionally use Insulin i.v to bring down a too high BG quickly. 

In an ideal world, no matter what kind of mix we're dosing, we could just tell the loop, and it would figure out how to carry on. For starters, I'd be happy if the data model wouldn't prevent it from  calculating a realistic and consistent amount of IOB and Acting Insulin.

I'm just worried that there's quite a few projects to coordinate when it comes to somthing as deeply rooted as the underlying data model.

**Comment by sulkaharo** [comment]
Some notes:

If we do port the IOB algorithm from OpenAPS over, we can simultaneously add the capability to define the DIA per treatment, so someone marking down long-acting treatments could mark down a 18 hour DIA. I'm not sure where we'd get the insulin curve data from though - someone would need to read through the data published on the longer insulins and figure out what DIA really is appropriate. This would probably also lead to discussions around what DIA is actually correct to implement, where OpenAPS is now enforcing a minimum of 5 hour DIA for fast-acting insulins given we know the actual action time is at least this long.

Second - the implementation will need to also be able to take temporary insulin profile changes into account, same as all the looping systems, which also means the IOB value correctedness will be dependent not only on all boluses having been marked down at the right moment, but also that the profile data is correct.

**Comment by PieterGit** [comment]
Postponing to a TBD release. It seems nobody is interested or has time to implement this feature. If this issue does not get attention before the 0.13.0 release, I will close it next time and label it: `closed-due-inactivity`
