### ISSUE TITLE
Temporary basal rate shown incorrectly after suspend/normal state

### ISSUE THREAD

**Issue by seittenj** [nightscout/cgm-remote-monitor#3289]
Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier?
- Occures with latest release 0.10.2 and haven't seen it before. I updated also uploader (indra 0.6.0). I'm not sure is this happening because of uploader or nightscout itself.

Which device / browser version was used to reproduce the bug?
-I have been using Android devices (based on Android 7.0) and Chrome browser

Does this happen every time you launch Nightscout, or sometimes?
Reprodusable. 

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)

- Set temporary basal for longer time, e.g. 10 hours, 0.15U/h
- Pump suspended before breakfast/meal, Nightscout showing this in UI correctly
- Breakfast/meal bolus given and temp basal continued (pump back to normal state)

Result: Nightscout UI is not showing anymore temp basal level or duration correctly. Graph is showing only normal basal rate (0.075) and basal field shows normal rate (0.075). 
Somehow also the duration/remaining time for basal rate is not shown correctly. There should be almost 5 hours in this example, but pump info is only showing 49 minutes.

How to recover:
If temporary basal is set again, Nightscout is again showing correct values.

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong
![image](https://user-images.githubusercontent.com/32077350/35472109-acd540f2-0371-11e8-9dfa-8c08f45a44fb.png)

**Comment by PieterGit** [comment]
@seittenj I don't know a indra uploader, but I do know the 0.6.0 version of oref0.
I know @jpcunningh created an enhancement to account for pump suspends, see
https://github.com/openaps/oref0/pull/879

@jpcunningh: can you confirm that your oref0 PR fixes this issue. If so, this Nightscout issue can be closed and upgrading to oref 0.6.1 (when available) will fix this.

**Comment by jpcunningh** [comment]
The OpenAPS update the account for pump suspends doesn't change the basal
line on NS. The update only affects the IOB calculation, so it would not
affect this issue.

From one perspective, it increased the amount of times when the basal line
doesn't reflect reality. However, NS shows the grey pump suspend and
unsuspend events, so making NS show the basal going to zero during suspends
hasn't bubbled up on my things to work on list yet.

Jeremy





On Feb 26, 2018 12:57, "PieterGit" <notifications@github.com> wrote:

@seittenj <https://github.com/seittenj> I don't know a indra uploader, but
I do know the 0.6.0 version of oref0.
I know @jpcunningh <https://github.com/jpcunningh> created an enhancement
to account for pump suspends, see
openaps/oref0#879 <https://github.com/openaps/oref0/pull/879>

@jpcunningh <https://github.com/jpcunningh>: can you confirm that your
oref0 PR fixes this issue. If so, this Nightscout issue can be closed and
upgrading to oref 0.6.1 (when available) will fix this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nightscout/cgm-remote-monitor/issues/3289#issuecomment-368647555>,
or mute the thread

**Comment by seittenj** [comment]
I have still seen this happening( ns showing wrong basal rate after pump suspend ), but it can be "fixed" also by reloading the ns webpage.

**Comment by seittenj** [comment]
This is the uploader sw(v. 0.6.1) I was referring to(uploader used with 640g) :
https://github.com/pazaan/600SeriesAndroidUploader/releases

**Comment by Pogman** [comment]
@seittenj the pump pill status info is created in the uploader and sent as status text to NS. You may have an issue related to the uploader as the pump pill should always be a snapshot of the pump status separate to what NS shows or calcs. Can you open an issue for that there?

There is a refresh/lag issue in NS with basals even when the data is there and correct ie. a browser refresh will show it. I've found a workaround for this: a manual NS treatment entry for a cancelled temp will use a 'duration = 0' entry to flag the return to normal basal, by also adding a 'percent = 100' entry to the data sent to NS will auto refresh as soon as it gets the data.

https://github.com/pazaan/600SeriesAndroidUploader/issues/206
