### ISSUE TITLE
add SSL cert info to Alexa plugin instructions 

### ISSUE THREAD

**Issue by dougboss** [nightscout/cgm-remote-monitor#3383]
The alexa plugin instructions need to be updated to reflect the new SSL requirements for Alexa
By alexa skill has been working for months and today when I attempted to update it to add more features now that Im looping, the wizard requires information on  SSL 

With 3 choices 
Does Heruko support SSL ?  
EDIT - Based on testing it looks like "My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority " is the right choice 
My skill is working again 

>>>>>>>>>>
Global Fields
These fields apply to all languages supported by the skill.

To protect your security and the security of end users, we require that you use a certificate while developing an Alexa skill.
For more information, see Registering and Managing Alexa Skills - About SSL Options.
Certificate for DEFAULT Endpoint:
Please select one of the three methods below for the web service:

- My

 development endpoint has a certificate from a trusted certificate authority

- My

 development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority

- I

 will upload a self-signed certificate in X.509 format. Learn how to create a self signed certificate.

>>>>>>>>>>>>> 
This is my first attempt at an issue so be gentle

**Comment by PieterGit** [comment]
@dougboss : Of course I'll be gentle. I have set this for the 0.11.0 milestone, because we are clearing the open issues to make sure we fix the issues needed for the next 0.10.3 release.

I think your refering to this page: https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/alexa-plugin.md
If you know what needs to be changed you can try to do it yourself. See
http://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html for more information about creating your first pull request. You need to use the Nightscout Github page instead of the openaps/oref0 one.

I don't have Alexa, so can't help you fix this issue. But I'm sure if you ask somebody at https://gitter.im/nightscout/public or https://gitter.im/nightscout/intend-to-bolus is able to help you solve this issue and guide you through the process of making you're first PR. 

Please give it a try, and ask for more help if you need id.

**Comment by dougboss** [comment]
Its working - I just needed to select the subdomain ssl choice ... Github still scares/confuses me a little but Ill attempt to edit ... its the least I can do to try to help the system that has been so helpful to me

**Comment by PieterGit** [comment]
@dougboss good to hear that you solved your issue. please help other to solve it by improving the docs. The people on the gitter will help you with your first PR if you get stuck.

**Comment by dougboss** [comment]
Just completed my first PR ... THANKS ...

**Comment by PieterGit** [comment]
@dougboss : I merged https://github.com/nightscout/cgm-remote-monitor/pull/3401
 and will be released with 0.10.3 version of the docs.

You see how easy it is to contribute! Feel free to do more contributions.

**Comment by dougboss** [comment]
I dont know if its now duplicated or if I just missed the text in Step 6 

But it looks like the edit I suggested just duplicated the content in step 6 

" Select the appropriate certificate type. For heroku this is typically "My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority"

I dont recall that being there but if  it was then my edit is merely the same information stated differently.  with some more detail ... 
I think
