### ISSUE TITLE
Release notes for upcoming 0.10.3 release

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#3691]
First start at changes from 0.10.2 to 0.10.3 release. Quite a list:

The last Habanero series release Purple (0.10.3) is here!

- New feature: `speech` plugin added.  Speech synthesis plugin. When enabled, speaks out the blood glucose values, IOB and alarms.
- New feature: `xdrip-js` plugin added. Integrated xDrip-js monitoring
- Nightscout now deals with mLab and other Mongo database outages better and shouldn't need a restart after an outage
- Nightscout web page loading is now more robust for people using Loop, OpenAPS, AndroidAPS or multiple uploaders
- Site navigation now links to multiple clock views
- Client color themes now has a new 'colorblindfriendly' scheme that works better for users with deuteranopia (and possible other forms of color blindness)
- Careportal. Add support for temp targets in mmol/l
- New plugin to track pump battery age (batteryage) has been added 

Other Changes & Bugfixes

- Over 250 commits, 118 files changed, +13,734 / −7,169 lines of changes
- Only locales that have language support are loaded as Moment.js locales, reducing the size of the javascript bundle
- upgrade to Node 8.11.x LTS. Use of Node 9 or Node 10 is not recommended
- upgrade to Npm 5.6.x or later. Npm 6.1.x is recommended. No support for Npm 5.x (x<4)
- upgrade a lot of upgrades to dependencies, including security fixes
- `forever` has been removed for Heroku startup with the `Procfile`
- upgrade mongodb client and support MongoDB 4.x
- README updated, especially Windows instructions
- Glucose variability report now works correctly with hourly filters and sorting
- activity data storage API has been added (but no visualization for the data yet, scheduled for a later release)
- `PUMP_WARNONSUSPEND` renamed to `PUMP_WARN_ON_SUSPEND`. Set to `true` to get an alarm when the pump is suspended.
- `DEVICESTATUS_ADVANCED` (`true`) - Now defaults to true. Users who only have a single device uploading data to Nightscout can set this to false to reduce the data use of the site.
- swagger and OPEN API restored, see `/swagger.yaml` or `/swagger.json`
- most language localizations have been improved but still need work! Please join the Nightscout Translators group for details on how to help!
- Updated docs for alexa plugin
- Careportal: add Pump Battery Change event
- TDD average on daytoday report (total daily dosage)

We recommend Azure users consider migrating their hosting to Heroku, as we've observed Heroku users have significantly less issues with having their sites work reliably. If you want to continue using Azure, *change the following configuration variables in Azure before updating* to the latest Nightscout version:
```
WEBSITE_NODE_DEFAULT_VERSION=8.11.1
SCM_COMMAND_IDLE_TIMEOUT=300
```
Install instructions can be found: https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md#install

The release coordination for this release was done by @PieterGit and @sulkaharo. 
We would like to thank the following people for their contribution (in alphabetical order): @2flea, @aaronjknox, @AdrianLxM, @apanasef, @bogdangorescu, @brutevinch, @Dave2526, @dbeasy, @dideldum, @dm61, @dougboss, @h2oil, @HenrikHL, @herzogmedia, @hichameyessou, @hummelstrand, @jaylagorio, @jasoncalabrese, @jimrandomh, John Weston, @jpcunningh, @Kdisimone, @kretch, @lsandini, @mdomox, @MilosKozak, @mpangburn, @norbertgaal, @pedrojparedes, @PieterGit, @PoweRGbg, @rhdtv2002, @ScheddyD, @schmitzn, @scottleibrand, @someoneAnyone, @sulkaharo, @tanja3981, @Tornado-Tim, @unsoluble, @veryfancy, @whooze, @winni67.

See https://github.com/nightscout/cgm-remote-monitor/milestone/10 for an (incomplete) list of issues and PR's fixed in this PR. See <<ADD URL TO MERGING PR>> for a complete list of changes.

Did I forget anything?

**Comment by jaylagorio** [comment]
Thanks for tagging me in this! It was the reminder I needed to update the documentation as promised. Lots of dependencies and installation steps were removed, this is much more streamlined now. Thank you!

**Comment by herzogmedia** [comment]
Hi, Lukas Herzog and @herzogmedia is both me, so you can delete one of those. 
Thanks for all your efforts!

**Comment by mdomox** [comment]
Did you notice tha after a while, app crashes ? I get the following in my logs. 

2018-07-30T07:42:00.122509+00:00 heroku[router]: at=error code=H10 desc="App crashed"

**Comment by PieterGit** [comment]
@mdomox : is that with the most recent dev? Please lookup into your Heroku logs to find more info on why it crashes (e.g. by restarting the dynos). We've seen some crashes during this cycle, but don't have the start of the logging of those crashes. If you can find them, please create a issue.

**Comment by mdomox** [comment]
@PieterGit I am logged in to papertrail. Tell me what to search for in the logs.

**Comment by mdomox** [comment]
@PieterGit , Voila

Jul 30 00:27:37 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:entries:read 
Jul 30 00:27:37 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:entries:create 
Jul 30 00:27:37 maria-cgm app/web.1: got data-received event, requesting reload 
Jul 30 00:27:37 maria-cgm app/web.1: If-Modified-Since: Invalid Date Last-Modified 2018-07-30T07:03:07.461Z 
Jul 30 00:27:37 maria-cgm heroku/router: at=info method=POST path="/api/v1/entries" host=maria-cgm.herokuapp.com request_id=82d31e49-42a5-4f3a-8857-5e67d32471e7 fwd="5.144.229.1" dyno=web.1 connect=0ms service=243ms status=200 bytes=1145 protocol=https 
Jul 30 00:27:38 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:devicestatus:read 
Jul 30 00:27:38 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:devicestatus:create 
Jul 30 00:27:38 maria-cgm app/web.1: /app/node_modules/mongodb/lib/utils.js:132 
Jul 30 00:27:38 maria-cgm app/web.1:       throw err; 
Jul 30 00:27:38 maria-cgm app/web.1:       ^ 
Jul 30 00:27:38 maria-cgm app/web.1: TypeError: Cannot read property 'ops' of null 
Jul 30 00:27:38 maria-cgm app/web.1:     at /app/lib/server/devicestatus.js:13:20 
Jul 30 00:27:38 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 00:27:38 maria-cgm app/web.1:     at session.endSession (/app/node_modules/mongodb/lib/utils.js:399:27) 
Jul 30 00:27:38 maria-cgm app/web.1:     at ClientSession.endSession (/app/node_modules/mongodb-core/lib/sessions.js:72:41) 
Jul 30 00:27:38 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:397:17) 
Jul 30 00:27:38 maria-cgm app/web.1:     at /app/node_modules/mongodb/lib/collection.js:626:14 
Jul 30 00:27:38 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 00:27:38 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:404:25) 
Jul 30 00:27:38 maria-cgm app/web.1:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55) 
Jul 30 00:27:38 maria-cgm app/web.1:     at resultHandler (/app/node_modules/mongodb/lib/bulk/ordered.js:457:16) 
Jul 30 00:27:38 maria-cgm heroku/web.1: State changed from up to crashed 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=LdX3w04zLXZst8XjAAAD&transport=websocket" host=maria-cgm.herokuapp.com request_id=9de35cd3-dbf5-414f-9049-8bef23cfe5bf fwd="5.144.229.1" dyno=web.1 connect=0ms service=8121ms status=101 bytes=129 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/web.1: Process exited with status 1 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=cHk0djuM2zlq8mLYAAAB" host=maria-cgm.herokuapp.com request_id=ef652589-1fb4-4cbb-951b-73f6f1895d9d fwd="87.203.121.205" dyno=web.1 connect=1ms service=12299ms status=101 bytes=175 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/router: at=error code=H13 desc="Connection closed without response" method=POST path="/api/v1/devicestatus" host=maria-cgm.herokuapp.com request_id=4fbe7a75-03b3-4c40-a7a0-f11a35727be5 fwd="5.144.229.1" dyno=web.1 connect=0ms service=105ms status=503 bytes=0 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=pF5KjkyyYOU7SuYlAAAE&transport=websocket" host=maria-cgm.herokuapp.com request_id=8134999b-02f6-4937-9bbc-3a07c341c24c fwd="31.152.26.140" dyno=web.1 connect=0ms service=5624ms status=101 bytes=129 protocol=https 
Jul 30 00:27:39 maria-cgm heroku/router: at=error code=H10 desc="App crashed" method=POST path="/api/v1/devicestatus" host=maria-cgm.herokuapp.com request_id=a3541034-f572-4021-92e8-779f4486284d fwd="5.144.229.1" dyno= connect= service= status=503 bytes=

**Comment by mdomox** [comment]
@PieterGit . Restarted and crashed again. 

Jul 30 01:02:37 maria-cgm app/web.1:      openaps: { suggested: [Object], iob: [Object] }, 
Jul 30 01:02:37 maria-cgm app/web.1:      uploaderBattery: 92, 
Jul 30 01:02:37 maria-cgm app/web.1:      created_at: '2018-07-27T09:25:33Z', 
Jul 30 01:02:37 maria-cgm app/web.1:      NSCLIENT_ID: 1532683533945 } } 
Jul 30 01:02:37 maria-cgm app/web.1: /app/node_modules/mongodb/lib/utils.js:132 
Jul 30 01:02:37 maria-cgm app/web.1:       throw err; 
Jul 30 01:02:37 maria-cgm app/web.1:       ^ 
Jul 30 01:02:37 maria-cgm app/web.1: TypeError: Cannot read property 'ops' of null 
Jul 30 01:02:37 maria-cgm app/web.1:     at insertResult (/app/lib/server/websocket.js:371:26) 
Jul 30 01:02:37 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 01:02:37 maria-cgm app/web.1:     at session.endSession (/app/node_modules/mongodb/lib/utils.js:399:27) 
Jul 30 01:02:37 maria-cgm app/web.1:     at ClientSession.endSession (/app/node_modules/mongodb-core/lib/sessions.js:72:41) 
Jul 30 01:02:37 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:397:17) 
Jul 30 01:02:37 maria-cgm app/web.1:     at /app/node_modules/mongodb/lib/collection.js:626:14 
Jul 30 01:02:37 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 01:02:37 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:404:25) 
Jul 30 01:02:37 maria-cgm app/web.1:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55) 
Jul 30 01:02:37 maria-cgm app/web.1:     at resultHandler (/app/node_modules/mongodb/lib/bulk/ordered.js:457:16) 
Jul 30 01:02:37 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=ck2PYx92m6nYSkFvAAAB&transport=websocket" host=maria-cgm.herokuapp.com request_id=1216ce0c-7c6f-4ec7-84f5-fa6c22eda459 fwd="31.152.26.140" dyno=web.1 connect=0ms service=32899ms status=101 bytes=129 protocol=https 
Jul 30 01:02:37 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=DIPfKHINyx2KM46mAAAC" host=maria-cgm.herokuapp.com request_id=291ef480-0ada-43cd-bb92-9b512bff0898 fwd="87.203.121.205" dyno=web.1 connect=0ms service=31925ms status=101 bytes=175 protocol=https 
Jul 30 01:02:37 maria-cgm heroku/web.1: Process exited with status 1 
Jul 30 01:02:38 maria-cgm heroku/web.1: State changed from up to crashed 
Jul 30 01:02:38 maria-cgm heroku/web.1: State changed from crashed to starting

**Comment by mdomox** [comment]
@PieterGit All the above happens with dev and 0.10.3 branch. Loaded master and it has not happend so far...
