### ISSUE TITLE
help wanted profile questions

### ISSUE THREAD

**Issue by MarcDencker** [nightscout/cgm-remote-monitor#3722]
we use the spike app with nightscout and have  a few questions as we are new to both:

how do I track lantus in my profile?
what is a good carb activity absorption rate
my son is a competive swimmer, I would love it to be possible to easily switch carb absorption rates (profiles?)

**Comment by PieterGit** [comment]
@MarcDencker Please use a Gitter channel or Facebook for questions like this instead of the issue tracker for bugs/features to Nightscout. I don't know a good place for the spike community. 
For Nightscout questsions please use https://gitter.im/nightscout/public
For information about carb rates I would suggest https://gitter.im/nightscout/intend-to-bolus

Since I would like to help your, here's my attempt at giving answers to your questions:

1) Nightscout currently has no support of various insulines, that a feature request, see https://github.com/nightscout/cgm-remote-monitor/issues/2961

2) carb activity absorption rates differ quite a lot. For openaps/oref0 there is a feature called autotune, see https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/understanding-autotune.html
There is a new feature that will land in the 0.11 release that will make it possible to use autotune for Nightscout, see https://github.com/nightscout/cgm-remote-monitor/pull/3191

3) most pump users can use more than one pump profile. Loopers have possibilities like activity mode. Within Nightscout it's possible to create more profiles and to switch between profiles.

Closing this issue, becuase the issue tracker is not meant as a help forum.
