### ISSUE TITLE
Add Pushover for CGM readings that would trigger alarms

### ISSUE THREAD

**Issue by mstine** [nightscout/cgm-remote-monitor#375]
I recently updated everything to Dreamsicle, and I noticed the new features around using Pushover for sending treatments. I'm a Java programmer by trade and have only dabbled in Node, so I've resisted this for awhile.

I've long considered adding a push feature around sending CGM readings that would otherwise trigger an alarm. My iPhone has company policies applied that won't allow me to keep it from locking/sleeping, so I am unable to receive alarms from the browser unless I actively check it.

The Pushover code looked straightforward enough, so I'm guessing there might be other reasons why sending CGM readings wasn't attacked first. Would love to hear about those if they exist.

I've also considered using an SMS API. The other night my wife and I were at a concert and we couldn't get ANYTHING that used data to work, but phone calls and SMS worked fine. I'd really like to be able to get readings in those circumstances. http://textbelt.com looks like a fairly low friction path.

Thoughts?

Thanks,

Matt

**Comment by jimsiff** [comment]
I think that @jasoncalabrese has been experimenting with various Pushover alerts as well as two-way communication to acknowledge and silence alerts.  There is also an android-uploader branch maintained by @darrylschick that integrates SMS into the uploader rather than the cgm-remote-monitor.  I'm not sure of the status / timeframe for either Pushover or SMS to be integrated into the mainline code.

**Comment by darrylschick** [comment]
@mstine The SMS uploader addition I implemented uses native SMS in the uploader phone.  This is a great solution for the many people who don't have wireless data coverage (live in the mountains, etc) who can't use Nightscout because of that.  Feel free to check it out - the source is here https://www.dropbox.com/sh/wbwz0cid6ppatku/AADD14DUoQzXeOTuWPdGwDLXa?dl=0 Also there is an updated APK at Nightscout.info/labs with mmol support (will have source code posted for that soon)

**Comment by kenstack** [comment]
Jim - I use pushover for alerts in my own alert code and @jasoncalabrese and I have discussed a few times.  He has valid concerns over loudness and length of alarm with the default alarms in terms of waking people up.  Couple of thoughts:

1. before emergency alarms were implemented in pushover I simply sent 2 of the long loud ones if the time was past 10pm and before 7am - that works for me
2. more recently they added an emergency push notification (-2 designation) that requires feedback from the user (ie hit OK).  You can tell the api how often to send another push if you dont get a receipt back that they pushed ok - I havent bothered to implement this one because the doubles work for me but it looks fairly robust.  You may be able to implement the mute length with this return like current NS but I havent tried.

That said jason has a good point compared to the default browser music NS uses now - pushover is very robust and works well but could use louder alarms for wakeups.

**Comment by jasoncalabrese** [comment]
I've been using pushover server-side, but I don't think it's good enough for the mainline yet.  You're welcome to give it a try.

The best way to do that is to create a new branch off master and then merge https://github.com/jasoncalabrese/cgm-remote-monitor/tree/wip/push-notify into it

**Comment by darrylschick** [comment]
@jasoncalabrese Where is the dreamsicle code?  I think the /dev branch is Cookiemonster and that's what I worked from for the most recent SMS update.

**Comment by jasoncalabrese** [comment]
This plus a lot more is in dev now

**Comment by darrylschick** [comment]
Hey Jason, do you mean that a SMS feature is in development?

**Comment by scottleibrand** [comment]
Not SMS, but equivalent functionality from Pushover and IFTTT. 

-Scott




On Sat, Jul 11, 2015 at 9:44 PM -0700, "Darryl Schick" <notifications@github.com> wrote:










Hey Jason, do you mean that a SMS feature is in development?

**Comment by jasoncalabrese** [comment]
Yeah, with the IFTTT maker integration you can send sms, email, turn on lights, so anything else available with IFTTT

**Comment by darrylschick** [comment]
That’s great news, thanks for working on it.  I regret that I’ve been out of the loop on this since the SMS prototype I did some months ago, the work requirements of my business have become overwhelming this year.

**Comment by sulkaharo** [comment]
Darryl no worries! We've done huge refactoring to the codebase and it's starting to make this type of improvements much easier than even a month ago, and some stuff is becoming "free" as a result of the integration work. :) I'm sure you'll love working on the newly structured codebase if you get your hands dirty again in the future. ;)

Sulka
