### ISSUE TITLE
Heroku Database to big after 6 month usage?

### ISSUE THREAD

**Issue by tremor** [nightscout/cgm-remote-monitor#3767]
After using Nightscout with xDrip+ with Data from an Libre Freestyle and MiaoMiao Transmitter mLabs sends me and mail that my Size in Disk is over 496 MB. (Currently 1 GB) with over 384 MB in the entries collection. Compacting the database via the Webinterface from mLab does not help substainly. 

How can I delete old entries (for example older then 4 Month) in the NightScout Webinterface? 

I only find how to delete entries in the future, but not in the past.

**Comment by khind** [comment]
Maybe with "Studio 3T" for the MongoDB.

**Comment by PieterGit** [comment]
@tremor About cleaning your Mongodb database:
@jpcunningh has prepared a PR for this, see https://github.com/nightscout/cgm-remote-monitor/issues/3767 for the upcoming 0.11 release. Can you please test that PR and report your findings there?

The procedure is also documented with the OpenAPS/oref0 community here, see
https://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Rig-NS-communications-troubleshooting.html#mlab-maintenance

**Comment by PieterGit** [comment]
@tremor Can you give an update if you have solved this issue? I merged https://github.com/nightscout/cgm-remote-monitor/pull/3821 to dev today, which might be helpfull for this problem. Please close this issue if it's resolved for you.

**Comment by tremor** [comment]
I finally deleted the whole collection 'entries' and do a fillback from xdrip for the last 3 months - it took a little bit over 10 Minutes and now the size is below 100 MB and I only had to manually trigger a compact database via the support. Not the best solution but at least it works again!

**Comment by PieterGit** [comment]
@tremor  @khind Closing this issue because I think enough has been done for 0.11 for now by @jpcunningh . The logging has been improved in https://github.com/nightscout/cgm-remote-monitor/pull/4004
And there is a new feature to delete devicestatus entries, see https://github.com/nightscout/cgm-remote-monitor/pull/3821

If people (with a full mongodb) can confirm that these two functions work as expected, please confirm it in the respective PR's by adding a comment.
