### ISSUE TITLE
Enhancement - API access to reports

### ISSUE THREAD

**Issue by briandlucas** [nightscout/cgm-remote-monitor#3868]
looking for means to programmatically download reports, specifically daily stats report.  one better, scheduled report export with email functionality.

i know there is an API but looking for nicely formatted with charts, etc.

**Comment by PieterGit** [comment]
@briandlucas what format do you want those reports in? html or excel? 
Are you able to work on creating pull requests for this? 
We can help you get acquainted with the Nightscout codebase, but you must learn or know how to program nodejs/javascript .

**Comment by briandlucas** [comment]
Short answer is probably, given enough time

Longer answer is I’m a reformed software architect that likes to tinker. Wrote my first JavaScript 20 years ago and so much has changed. I have written a few node apps that run internally as helper apps and for home automation integration. Basic stuff and nothing fit for production.

How do I get a feel for the magnitude / scale of effort? Not even sure where to start...

**Comment by PieterGit** [comment]
@briandlucas well, please contribute, and we'll help you if you get stuck and we'll review your PR and make sure it's fit for production. First steps is use an IDE (e.g. Webstorm) or just a plain editor (Notepad++ or VI or whatever) and begin with cloning https://github.com/nightscout/cgm-remote-monitor/tree/dev (use `dev` branch for new developments) and use the `make` for running test unit tests.

The report files are `lib/report_plugins`  

The magnitude / scale of effort is depending on your wishes and your programming skills. I'm pretty sure you can do that if you invest time in it and ask for help when you need it.

Please read @danamlewis blog article from a while ago https://diyps.org/2017/03/19/tips-for-troubleshooting-diy-diabetes-devices-openaps-or-otherwise/ . I was looking for a blog of Dana about contributing but couldn't find it. TL/DR: just start, and you can make a good contribution.

**Comment by briandlucas** [comment]
needs some guidance...

setup development env but have run into issues: 
1) attached to remote node process on my "production" nightscout server but am unable to break at anything that resembles report code.  breakpoints in main sections of code work but code bounces around and i can't find entry into report section(s).
2) running nightscout on development box loads and seems to run (with console out all looking appropriate) but browser hangs on "Loading the client"

any thoughts?

would like to look into this enhancement and figure out why my time is off on other reports.

Thanks!
