### ISSUE TITLE
Dexcom G5 share sso authentication problem

### ISSUE THREAD

**Issue by cmcsynth** [nightscout/cgm-remote-monitor#3921]
Hi thanks for your great work on this project
I'm using latest cgm-remote-monitor (Habanero Purple patch 0.10.3.1), deployed on Heroku.
Application works, but I'm not able to view data from Dexcom share.

I setted all parameters:
ENABLE: careportal basal bwp iob cob cage sage iage azurepush **bridge**
BRIDGE_SERVER: `EU`
BRIDGE_USER_NAME: `<myownusername>`
BRIDGE_PASSWORD: `<myownpassword>`

The credentials are the same as my dexcom account and I can access the dexcom site with them.

From application logs:

`<OnlineException DateThrownLocal="2018-09-12 16:51:32.0695709+00:00" DateThrown="2018-09-12 16:51:32.0695709+00:00" ErrorCode="SSO_AuthenticatePasswordInvalid" Type="15" Category="1" Severity="2" TypeString="SingleSignOn" CategoryString="System" SeverityString="Severe" HostName="" HostIP="" Id="{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}" Message="Simulate SSO: Authentication failed. AccountId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" FullText="Dexcom.Common.OnlineException: Simulate SSO: Authentication failed. AccountId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" />
`
Could you help me?
Thanks in advance

**Comment by francescaneri** [comment]
Enable: azurepush?

**Comment by cmcsynth** [comment]
Hi Francesca,
azurepush is enabled. 
It doesn't work even without that parameter.

**Comment by PieterGit** [comment]
@cmcsynth did you have this same configuration with Habanero Red (0.10.2)?
See https://github.com/nightscout/cgm-remote-monitor/releases/tag/0.10.2

I made some security fixes to the share2nightbridge in 0.10.3 because of security issues, but others reported success: https://github.com/nightscout/cgm-remote-monitor/issues/3734

Can you see if the problem also exists with 0.10.2? If that works, we might need to find out why it doesn't work for you (but works for others). Maybe it's because your using the EU Bridge server.

Please ask for more help on https://gitter.im/nightscout/public and we might find the root cause. I don't use share2nightscout bridge

**Comment by unsoluble** [comment]
0.10.3.1 bridge on EU here, no issues. I’d triple-check for typos, re-entering the auth fields from scratch. Also try changing your Dexcom password, then try again in NS with that.

**Comment by cmcsynth** [comment]
After changing password of Dexcom account It works like a charm.
thanks you for your great support

**Comment by PieterGit** [comment]
CLosing issue. @cmcsynth reports success after changing the Dexcom password.
