### ISSUE TITLE
Treatment visualizations missing under Dreamsicle

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#401]
Just pulled the latest master and looks like treatments that don't have a BG value aren't visualized. For example, the following treatment is not drawn:

{
    "enteredBy": "Sulka",
    "eventType": "Carb Correction",
    "carbs": "3",
    "created_at": "2015-02-08T14:25:54.168Z"
}

**Comment by jimsiff** [comment]
I can't reproduce on my 0.6.2 site in mg/dL.  Here are two 4c carb corrections...

![screen shot 2015-02-08 at 12 16 12 pm](https://cloud.githubusercontent.com/assets/6069420/6098200/6adedd2a-af8c-11e4-9c28-523e4823ff71.png)

{
    "_id": {
        "$oid": "54d7a4bafa0a280300740889"
    },
    "enteredBy": "",
    "eventType": "Carb Correction",
    "carbs": "4",
    "created_at": "2015-02-08T18:02:34.457Z"
}

{
    "_id": {
        "$oid": "54d7c259fa0a2803007408a4"
    },
    "enteredBy": "Dad",
    "eventType": "Carb Correction",
    "carbs": "4",
    "created_at": "2015-02-08T20:08:57.171Z"
}

I did however notice that when I switched my site to mmol, my breakfast bolus entry disappeared.  Is that possibly due to the 'treatment data stored as strings' issue that you found recently?

![screen shot 2015-02-08 at 12 20 12 pm](https://cloud.githubusercontent.com/assets/6069420/6098228/1575f520-af8d-11e4-844a-64811910ca6e.png)

**Comment by sulkaharo** [comment]
The treatments also don't store the units and use the display units at the time of storing, so the code currently assumes the units in the treatment object are the display units at the time of display. Hence if you switch between units, the treatment visualisation is more or less guaranteed to break in interesting ways.

We're on mmol, probably is part of why this is broken.

**Comment by francescaneri** [comment]
hi guy ,
I wanted to point out that you can only enter data in one day and not the next or previous day . You can not change the data entered . thanks Matteo

**Comment by jimsiff** [comment]
@francescaneri yes, correct.  The current code  doesn't allow for data entry for previous or next day.  It's on the very long list of things to do.  Editing entries will not be allowed until the website supports user authentication.  If you want to edit or delete entries, you can do it manually from the Mongolab website by editing the documents in your treatments collection.

**Comment by francescaneri** [comment]
@jimsiff thanks for the explanation ;)

**Comment by jasoncalabrese** [comment]
Think that has been resolved also, if there are still treatments that don't get displayed we can reopen this
