### ISSUE TITLE
Optional force automatic redirections to HTTPS if HTTP is used by mistake

### ISSUE THREAD

**Issue by jweismann** [nightscout/cgm-remote-monitor#4010]
First off, let me use this opportunity to express my gratitude for all your hard work on this awesome project. Speaking of which, now that heroku has become the recommended platform for hosting, there is one thing that bothers me, namely that heroku doesn't support automatic redictions to HTTPS. 
 
If one (by mistake) types HTTP in the URL or if HTTP happens to be the default choice of a given browser and one (again by mistake) doesn't pay attention then the site will be served via HTTP. For some this is fine. Personally, I would prefer either an error code or an automatic redirection to HTTPS. To the best of my knowledge this is not supported directly by the heroku platform so it has to be supported in the app itself. I guess something like this (in app.js) would serve the purpose and optionally support this behaviour:

     app.set('title', appInfo);
     app.enable('trust proxy'); // Allows req.secure test on heroku https connections.
+    if (env.settings.isEnabled('httpsredirection')) {
+        console.info('Enabled httpsredirection: redirect http to https');
+       app.use((req, res, next) => {
+            if (req.header('x-forwarded-proto') !== 'https')
+                res.redirect(`https://${req.header('host')}${req.url}`)
+            else
+                next()
+        })
+    }
     app.set('view engine', 'ejs');
     // this allows you to render .html files as templates in addition to .ejs
     app.engine('html', require('ejs').renderFile);

That is, if not enabled it work the same way as today, both http:// and https:// will work. If enabled all http:// requests will be directed to similar https:// requests.

Please let me know if you consider this relevant and thanks again for all your hard work on this project. We are many that are truly grateful for your efforts.

**Comment by jweismann** [comment]
Sorry, the code part wasn't readable. Trying to use the markup instead and see if that improves it

`     app.set('title', appInfo);
     app.enable('trust proxy'); // Allows req.secure test on heroku https connections.
+    if (env.settings.isEnabled('httpsredirection')) {
+        console.info('Enabled httpsredirection: redirect http to https');
+       app.use((req, res, next) => {
+            if (req.header('x-forwarded-proto') !== 'https')
+                res.redirect(`https://${req.header('host')}${req.url}`)
+            else
+                next()
+        })
+    }
     app.set('view engine', 'ejs');
     // this allows you to render .html files as templates in addition to .ejs
     app.engine('html', require('ejs').renderFile);
`

**Comment by jweismann** [comment]
Sorry for the missing code markup above. Hopefully this is more readable:

```javascript
     app.set('title', appInfo);
     app.enable('trust proxy'); // Allows req.secure test on heroku https connections.
+    if (env.settings.isEnabled('httpsredirection')) {
+        console.info('Enabled httpsredirection: redirect http to https');
+       app.use((req, res, next) => {
+            if (req.header('x-forwarded-proto') !== 'https')
+                res.redirect(`https://${req.header('host')}${req.url}`)
+            else
+                next()
+        })
+    }
     app.set('view engine', 'ejs');
     // this allows you to render .html files as templates in addition to .ejs
     app.engine('html', require('ejs').renderFile);
```

**Comment by PieterGit** [comment]
@jweismann : this feature was on my wishlist as well. Can you try to create a pull request againt the `dev` branch instead of creating code in an issue? See https://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html or use a Git tool like SourceTree. 

Some remarks about your implementation:
- Environment variables should be documented in the readme and are always be written in capital letters. I would prefer to use a `INSECURE_USE_HTTP (default false)`. If  set to `true` don't redirect. If not set or set to `false`  we should redirect
- The solution should also work for non Heroku hostings.  See also these lines
https://github.com/nightscout/cgm-remote-monitor/blob/7c272ec67a7795e0f4edf7ff9abdfac1bd1308a0/server.js#L39-L51
- We probably might also use `request.secure` for non Heroku environments, see https://jaketrent.com/post/https-redirect-node-heroku/

Optional extra's (can be in a different PR): 
- also send hsts header, https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by jweismann** [comment]
@PieterGit Sure - if you consider it relevant too, I will create a PR. I was just doing the code snippet to express the idea. This week is very busy for me but I would like to have it in the coming release. What's the deadline you are targeting ? As for testing of non-Heroku hosting, I might still have my azure account but beside that I only have access to heroku. 

Finally, I like your idea of having redirections as default but this requires testing on non-Heroku hosting that I cannot commit to (besides azure, that is). We could play more safe and stick to the current situation as default and users would then have to make active changes to their settings to become exposes to this. Just a thought.

Thanks for your comments! I will dive on those when I prepare the PR.

**Comment by PieterGit** [comment]
@jweismann You don't have to commit to testing all configurations. We can work together, and use the communtiy. Adding the help-wanted label.

I looked into `http2` as well, and I think we can upgrade the current `SSL` configuration to use the new `http2` module of Node and `greenlock-exprees`, https://git.coolaj86.com/coolaj86/greenlock-express.js to use Letsencrypt SSL certificates out of the box.

So there are 3 configurations that this future PR should be tested with:
- Heroku
- SSL / http2
- With a nginx or Apache in front.

Azure currently has no Node 8.12.x and there is not much interest of testing stuff on Azure. 
If this get worse, I think we should drop Azure from the hosting options for 0.12.x release.

I think @scottleibrand uses the Apache as fronted. 
I think he can help us out in making a PR that works there.

I currently set the date for the feature freeze at november 1st and then release approx. december 1st. But that's mainly my own goal of releasing earlier and more often.  We should at least test PR's like this on several configurations for 2-4 weeks and make sure the documentation and upgrade docs are ok.

**Comment by PieterGit** [comment]
@jweismann Others can help testing.  Azure does not have Node 8.12.x yet, and there is not much interest in testing Azure and Azure often has issues. If there is no one stepping up to take ownership for Azure hosting of Nightscout and think we should decide to drop Azure support soon.

I think there are three possible deployments this future PR should be tested with:
1.  Heroku
2.  Node SSL based
3.  With nginx or Apache in front of Node 

I think @scottleibrand uses Apache in front of Node Nightscout, and I'm pretty sure he can help out on thinking what the best way is. Perhaps we should require front-end servers to set `X-Forwarded-Proto` to `https` starting from Nightscout 0.11.x

Yesterday I looked into upgrading the Node SSL to a Node `http2` with Greenlock-express, see https://git.coolaj86.com/coolaj86/greenlock-express.js and https://git.coolaj86.com/coolaj86/greenlock-express.js/src/branch/master/examples/http2.js . That would not only take care of encryption but also on creating the Letencrypt SSL certificates.

I'm planning on doing a feature freeze at approx November 1st, but this is mainly my own goal. We should test 2-4 weeks with different configurations and I was hoping we could release 0.11 at approx December 1st.

**Comment by PieterGit** [comment]
This issue is outdated. See https://github.com/nightscout/cgm-remote-monitor/pull/4044 for more info and a PR.

**Comment by stavlor** [comment]
Hmm, I could be mistaken but I'm using an nginx infront of node setup and this doesn't affect API but appears to break the actual site in this config.

**Comment by stavlor** [comment]
Site just repeatedly does this 
![image](https://user-images.githubusercontent.com/1867987/52648152-025ab200-2eb4-11e9-9135-02959a1ee9b6.png)

**Comment by daveewall** [comment]
I had the same problem.  My server’s drive recently died, and I had to recreate my docker-compose images.  When I did this, my Nightscout image rebulit with the latest node (which was easily fixed in the Dockerfile), but then with the right version of node, it built the new master branch, which was 0.11, and I got a redirect loop, despite going to https first (evidenced in chrome devtools).  Both web browsers and the iOS app wouldn’t load.  I had to downgrade back to 0.10.3 and rebuild the docker image to get it working again.  Before downgrading, I tried setting the INSECURE_USE_HTTP to true, but the docker image still saw it as false, so I just downgraded so I can get back up and running.

That ENV part may be me forgetting to do something in docker-land properly, though.  I’d have to re-test to be sure, but the docker instance log showed it as false when it spits out that info with the HSTS variable.
