### ISSUE TITLE
Color-Clock: BG and trend arrow in one line

### ISSUE THREAD

**Issue by SlodkaOlga** [nightscout/cgm-remote-monitor#4233]
Hi!

I would like to have a second color-clock type page with BG and trend arrow in one line. This will be a great solution for old 7-inch tablets

Thanks!

**Comment by unsoluble** [comment]
I don't think the UI can reasonably support any more clock types. I had thought of eventually looking at making them modular somehow, so that things like the time and delta and arrow could be added/removed at will, and possibly rearranged in the layout. But that's a pretty major project that's off in the future somewhere.

If you want a custom version in the meantime, best to just tweak in your own fork.

**Comment by PieterGit** [comment]
@SlodkaOlga I would not wait, but start coding 😄 . If you need help feel free to ask for help at https://gitter.im/nightscout/public

Without doing stuff nothing will happen... Closing this issue for now. Feel free to reopen or PR a generic approach.

**Comment by SlodkaOlga** [comment]
if only I could... :D :D :D I will ask for help :)
