### ISSUE TITLE
feat: Simplify Profile storage

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4236]
**Describe the bug**
I noticed we use a `startDate`  at `profile` and at `profile>store>PROFILENAME` level. 
When you `Clone this record to new` all Stored profiles will be duplicated.

I also noted that when you clone it `profile.store.PROFILENAME.startDate` will be set to `1970-01-01T00:00:00.000Z` instead of the `startDate` at `profile.startDate` level.

**To Reproduce**
Use JSON editor for profile collection. Use browser to `/profile` 

**Expected behavior**
I wouldn't expect it to be possible to have to profile with the same name in two different records within the `profile` collection. I would expect we use a `startDate` and `endDate` and just several records within one collection. This makes browsing/ediing profiles cumbersome, and makes the code to find the right profile for a given timeperiod hard to grasp. I assume this also makes it possible to have multiple profiles with the same name and for the same period, that have different values. That doesn't make sense to me or I think any user.

**Screenshots**
My JSON editor view shows:
![image](https://user-images.githubusercontent.com/6500826/51793649-ea044b00-21c3-11e9-8ed0-0b78b7733c58.png)

**Your setup information**
Current `dev`.

**Additional context**
Found while debugging https://github.com/nightscout/cgm-remote-monitor/pull/4235
If there is a reason why the profiles are organized this way, please let me know why.
 
Should we refactor this with 0.12? Create a MongoDB index for `startDate` and `endDate` in the `profiles` collection and flatten the records. This will need some migration and UI support to go from 0.11 to 0.12 dataformat.

**Comment by philipgo** [comment]
I stubled upon your report after experiencing an error when trying to create a new profile. 

**To Reproduce**
I have a profile data record containing two profiles. When I either
a) "Clone this record to new" (the entire dataset) without making any further changes or
b) Add a third profile to the existing record
Nightscout will mix up the profile history in reports.

Correct profile history before profile changes:
![profiles correct](https://user-images.githubusercontent.com/29184757/53658589-78ec0380-3c59-11e9-9655-643d6162ee29.jpg)

Wrong profile history after making changes:
![profiles wrong](https://user-images.githubusercontent.com/29184757/53661659-2282c300-3c61-11e9-8987-f94bbecfb503.jpg)

The pattern of the mixup is not predictable, at least not for me.

@PieterGit Could you please let me know whether you think this is the same issue or whether I should file a separate report?

**Comment by philipgo** [comment]
I played a bit with the MongoDB entries for the record set. Neither changing the ```"startDate"``` of the individual profiles to a date after the creation of the record set nor changing the individual profile names to unique names fixes the mixup in our reports.

However, I think that the error might not lie where you suspected it to be. 

Start dates of a profile activation are saved in the treatments table as profile switches. These entries contain a complete JSON copy of the profile "as activated".  So I think the ```"startDate"``` entry in the profile records has no purpose.

It occured to me that my reporting error only concerns the profile names listed at the left end of the day to day graph. So it seems that instead of looking at the prior profile switch, the code makes other assumptions about what the active profile on that day was.

So the only change needed to make things work as expected might be fixing the selection of the profile printed at the left end of the day to day graph.

**Comment by philipgo** [comment]
@MilosKozak @sulkaharo I think you implemented the relevant parts of this. I am not very good at reading code: Am I correct that cgm-remote-monitor/lib/profilefunctions.js contains a function to identify the active profile at a given time? (e.g. start of a new day)

If so, could it be that this is wrongly used in cgm-remote-monitor/lib/report_plugins/daytoday.js ?

Profile switches during the day are displayed correctly in day to day reports, while the profile printed at the beginning of each day is often wrong.

**Comment by sulkaharo** [comment]
@philipgo Profile being wrong at the start of the day sounds like the reporting doesn't have the correct profile switch statement available for the start of the day. That part is all Milos' work and I personally think we should refactor the profiles so the profile data objects would be simpler and all contained in a single collection rather than mixing treatments and profile data the way it's now implemented, with the goal of making it easy to get the current profile for any given moment in time for reporting purposes. To fix this issue, I suspect we need a new API call for the REST API, as it's currently not possible to query for the relevant profile treatment in a sensible manner.

**Comment by jjaone** [comment]
Hi all, I ended up here when generating reports from a timeframe where I that two profiles with different "valid from dates" and found the GIT/NS issue about it and then asked about in NS/gitter where @viq pointed me here 👍

Seems this is a more complicated backend related problem, so that at this time frame I have not enough time to dive deep into solving it. 

Gotta revert using just one "default" profile which will of course make reports look quite inaccurate in those parts where profile changes are significant (e.g basal profile or daily stats of it in reports).

**Comment by PieterGit** [comment]
@MilosKozak can you give your take on this issue? According to @sulkaharo you invented this 😄 
Please let us know what you think that needs to be done, and we'll try to get volunteers to implement it in 0.12 or later.

**Comment by PieterGit** [comment]
Related issues: https://github.com/nightscout/cgm-remote-monitor/issues/3567 and https://github.com/nightscout/cgm-remote-monitor/pull/4250.

**Comment by PieterGit** [comment]
Didn't make it in 0.12.x
