### ISSUE TITLE
Add "minutes ago" to clock face

### ISSUE THREAD

**Issue by chrieke** [nightscout/cgm-remote-monitor#4363]
Hi, thank you for your great work.

Would it be possible to add the "5 min ago" value to one of the clock displays, preferably the color display. I know that the color display switches to grey if there have been no new values for 15-20min. But especially with a small child this is a long time and does not give the pre-kindergarden staff or parents at home the same sense of "security" as knowing that this is actually the most recent value.

I think this would not destroy the minimal style clock face, but greatly enhance the usability for many. The number shouldn't be too small, so that it can still be seen when displayed on a wall mounted tablet. 

If this is not wanted, maybe there is a chance to add a fourth clockface that could differentiate itself by showing even more information, e.g. the bg delta.
Thanks for considering this issue!

![image](https://user-images.githubusercontent.com/12833517/52827438-1de8d700-30c5-11e9-9a71-c295740a815b.png)

**Comment by unsoluble** [comment]
Hi there, I wrote the clock-color view. It was designed to serve a particular purpose — of being extremely clear to read on small devices from across the room — so I'm not really into complicating it further. Couple things tho:

You can change the time it takes to go stale (grey) in your own fork to suit your needs really easily — just look for `var staleMinutes = 13;` in `/views/clock-color.html`. Or, you could of course just insert your own time-elapsed that shows constantly, by tweaking the page to put `elapsedMins` where you want it.

There are lots of individual needs people have for these clock views — some want the delta, some want the time, etc. — but with three already listed in the UI we're up against reasonable limits there. The plan is to re-work the entire clock view structure so that it's more of a modular approach, so there's one view that you can customize with whatever parts you want. But that's a fairly large project that hasn't started yet — if you're familiar with CSS & JavaScript, would welcome any help you can offer.

**Comment by chrieke** [comment]
Hi, thanks for the detailed reply, that is super helpful. Reasonable thought process. A modular approach would def. be the best solution longterm. Little web dev. experience, but currently figuring out how I can best contribute to the community. Thanks again!
