### ISSUE TITLE
Reports- Day to Day- treatment timeline is not same scale as BG timeline

### ISSUE THREAD

**Issue by amoskane** [nightscout/cgm-remote-monitor#4485]
**Describe the bug**
Looking at a one day rendering, what does "^^^default^^^" mean and shouldn't the data start rendering at 12am instead of 7am? If not, why does treatment data never render between 12am-7am?  
https://www.dropbox.com/s/q3xi5wit29tzrsl/Screenshot%202019-03-18%2013.57.27.png?dl=0

**To Reproduce**
1. Go to 'Reports'
2. Click on 'one week'
3. Scroll down to 'one day's rendering'
4. See treatment data start at 7am even though I know I have treatment events between 12am and 7am

**Expected behavior**
See treatment events between 12am and 7am

**Your setup information**
- What version of Nightscout (0.10.2-release-20171201) is that just incredibly behind?? :)
-type of CGM, and how do you get your data there? G5, Spike
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? Does not seem to be, no. Same in Safari and Firefox. Have seen it before in Chrome too.

**Additional context**
I'd love to dig in and see why it renders that way, but wanted to confirm that it's not rendering correctly first. Can someone validate my experience and idea to correct- i.e., start rendering the treatments object at 12am?

**Comment by NickyJoel** [comment]
Hey,
I have a similar problem. For mine it just always shows the last two hours of my basal. Also it's 11:56a.m. on april 9th right now but it already shows the full 24h. I'm assuming somewhere in my set-up the time is wrong but I don't know where. In my live nightscout view everything is correct.
![Nightscout](https://user-images.githubusercontent.com/47711483/55791374-aaf54e80-5abe-11e9-809b-e088e98644bf.jpg)

**Comment by Lytrix** [comment]
I also have a similar problem with the latest master of May 1st 2019, main screen it's ok, but in reports it always shows only the last 2 hours.

<img width="1013" alt="Screenshot 2019-05-01 at 12 06 04" src="https://user-images.githubusercontent.com/4370175/57013071-0328f780-6c0a-11e9-8c55-c220fc7807c8.png">

**Comment by NickyJoel** [comment]
I solved it for me. In the profile editor I had chosen my ECT timezone, but when I changed it to the europe-city version all of a sudden it worked. Perhaps this may be your problem too?

**Comment by unsoluble** [comment]
Yup, the generic timezones appear to break in a number of strange ways. Best to always use one of the prefixed ones (like `Europe/...` or 'US/...`). We should really pare down the list (see #4003), just hasn't happened yet.

**Comment by 4gra** [comment]
Just commenting here since nobody answered one of the original questions, the text what "^^^default^^^" refers to the name of the profile that is (allegedly) active from that point on in the graph.  If you have only one profile, and it's appearing anywhere else except the start of the

**Comment by CarlHelberg** [comment]
Hey guys. Also had this issue and fixed it... well not fixed, but work around.
So the problem I had was the ^^^Default^^^ showing on the graph (I thought it was a bug since reporting was so broken) and then reporting not showing correctly.
I mean that I could see the BG levels in the graph but no extra info like insulin, carbs etc... JUST the green BG dots.

The fix is, as :point_up: @4gra said, Default refers to the profile, mainly the Name under db records in the profile.
So change the dbName in profile editor from "default" to "Nightscout" or whatever else you want, and the text on graph will change too.
The second issue, about the data not showing, my mongo sever is in virginia, so tried a bunch of US/ timezones, didn't work.
Setting the Timezone to ROC works and I can now see the data I needed.
