### ISSUE TITLE
device status grows fast and fills free mlab capacity, would capped collection help ?

### ISSUE THREAD

**Issue by CarnageMarkus** [nightscout/cgm-remote-monitor#4555]
**Feature Request/Question**

Hello, I just recently got to the point of **common "mLab" storage capacity**, where all APS and Nightscout systems stopped working out of blue. Since it was my first time with this "expected" crash, I was offline for some time. If it's not clear what I am talking about, mlab offers 496mb of free storage plan for mongodb. Where `devicestatus` collection grew quite big.

I feel that this could be quite easily avoided, by using `capped collection` for `devicestatus`. Correct me if I am wrong, but this collection seems relevant only for quite short time window -> few days at max for debugging of APS behaviour.
Therefore there is no need to hold all historical records, especially when it's the most updated collection (at least for OpensAps users it seems).
I am no database expert, but what I understand from [documentation](https://docs.mongodb.com/manual/core/capped-collections/), it cyclically replaces oldest records, holding only the few most recent. I think this would be useful to prolong "issue-free" time for users as it will keep the devicestatus collection at fixed size at all times. 

What are yours opinions on this ? Are there any issues why would it not work ?

**Comment by sulkaharo** [comment]
Capped collections don't support a lot of query mechanisms and thus would be hard to work with. We've discussed an alternative where a TTL index would be used to store something like last two weeks of device status data, which would effectively accomplish the same (and would be much easier to implement).

**Comment by CarnageMarkus** [comment]
That sounds great. 👍

**Comment by mtfoley** [comment]
hi @sulkaharo , I had a look at this and it seems like the devicestatus is storing the "created_at" field as strings instead of dates. In order to use a MongoDB TTL index, I think a different field would need to be stored alongside this one when a devicestatus record is created.  I think that the issues with that approach could be 1) that makes extra data storage with each record, 2) clients would probably have to ignore this field, or you'd somehow keep it from showing up in queries, and 3) you may need a way to apply this to existing data.

A different approach could be to provide a scheduled job that calls DELETE method on /api/v1/devicestatus/?find[created_at][$lte]=DATE. I'm looking around the NS code for scheduled jobs and i haven't seen them yet. 

If this approach has merit, perhaps it would become something that's available to manipulate from admin pages, so it isn't necessarily something that requires ENV variable options to change. Would love to hear your thoughts.
