### ISSUE TITLE
Nightscout crashed on Heroku last night... with an error at /pebble. Any ideas why?

### ISSUE THREAD

**Issue by someoneAnyone** [nightscout/cgm-remote-monitor#456]
Here is a the log papertrail caught for me. I ended up having to re-deploy from github to get it up and running again. I replaced sensitive info with XXXXX

Mar 02 17:58:33 XXXXX heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/pebble" host= XXXXX.herokuapp.com request_id=1bb5c20d-ba2a-48c9-8661-748d026f5898 fwd="XX.XX.18.106" dyno= connect= service= status=503 bytes=

**Comment by gregwaehner** [comment]
Pete –

Don’t know for sure, but I can tell you that my Heroku DB was down 88% of the last 24 hours, and 22% of the last 7 days. The error you got is telling me that you were getting an HTTP 503 error – nothing to do with the GitHub code… that’s an infrastructure HTTP service connection error…. So my guess, without knowing exactly what you did, is that when you “re-deployed” you did the auto-deploy… and when you did that, it created a new instance, on a new “up” server rather than the “down” server… That’s my guess based solely upon your one line of log data, and my uptime monitoring of my own Heroku.

 

-          Greg

**Comment by someoneAnyone** [comment]
I haven't seen the problem again. I don't have auto-deploy on for Heroku, I do it manually and before the crash it was running solidly. Must have been a temporary hiccup that I over reacted to.
