### ISSUE TITLE
alexa documentation

### ISSUE THREAD

**Issue by Mr-Enigma** [nightscout/cgm-remote-monitor#4583]
i cant seem to find the docs on how to setup the alexa skill? can anyone point me to it? many thanks

**Comment by unsoluble** [comment]
The link in the readme is broken, but the doc is still here: [https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md](https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md).

**Comment by WanaGo** [comment]
I am having real trouble getting Alexa to work with Nightscout, using the Documentation. Running latest version of Nightscout too. Followed the instructions to a T, and I have it working in the Amazon Development area, on the Test Page. However it will not work on any of my Alexa devices or even the Alexa App on my phone, even though its the same account and I can see the 'Nightscout' Skill and its enabled. It just wont work, Alexa seems to have no idea what Nightscout is, yet when using the same command in the test area it works fine. Tried voice and typing, and the results are the same.

**Comment by sulkaharo** [comment]
@wanaGo double check you’re using https for all the urls in the configuration

**Comment by WanaGo** [comment]
All that is fine sadly @sulkaharo

**Comment by mhaeberli** [comment]
I can't even get it to work on the test page. :-(

**Comment by inventor96** [comment]
@WanaGo My Alexa-enabled devices have had trouble recognizing what Skill I want to talk to while my Skill Name was "nightscout" (all one word). I've had significantly better results after setting it to "night scout" (two words). Give that a shot. If you still have issues, open a new issue for a discussion.

@mhaeberli #4980 has some significant updates to the Alexa integration, so you might try switching your Nightscout site over to the wip/013alpha branch and trying it out again.

@PieterGit Since we're aiming to clean up all the Alexa and Google Home issues, this one could probably be closed since the original issue has been fixed.

**Comment by PieterGit** [comment]
Closing issue as @inventor96 requested. New Alexa features/bug fixes should be done on the new Alexa/Google Home codebase of 4980.

**Comment by mhaeberli** [comment]
So to confirm, is this now in 13.01 master?

**Comment by inventor96** [comment]
@mhaeberli Yes, nothing has changed with this since the issue was fixed, so it will be in the latest version.
