### ISSUE TITLE
API reporting incorrect delta

### ISSUE THREAD

**Issue by cascer1** [nightscout/cgm-remote-monitor#4693]
**Describe the bug**
The delta reported by the API (for example `/api/v1/entries/sgv.json?count=2`) is different from the actual BG delta. 

**To Reproduce**
1. Observe delta reported by xDrip (in the xDrip app)
2. Calculate actual delta (using last two readings, should be the same as xDrip)
3. Observe delta reported by Nightscout (not API, should also be the same as xDrip)
4. Observe delta reported by API (this is often different)

**Expected behavior**
The BG delta reported by the API should be the same as the delta displayed in Nightscout.

**Screenshots**
[Recording displaying discrepancy](https://i.eliens.co/1560937263212.mp4)

**Your setup information**
- Nightscout version 0.11.2-rc2-20190323
- Dexcom G6 with xDrip

**Comment by sulkaharo** [comment]
The API returns the data recorded by the application storing the data, where the delta values are not recalculated by the API but are the ones stored by the app. This sounds like xDrip is storing different delta values to the database than what are being displayed. That -6.5 delta is also clearly wrong, since mg/dl units should never be stored as fractions. Let's make a ticket to to the xDrip repo.
