### ISSUE TITLE
Request Heartrate eventType option in Careportal 

### ISSUE THREAD

**Issue by ryanchen26** [nightscout/cgm-remote-monitor#4899]
I'm the developer of the Fitbit Sentinel clockfaces for monitoring CGM data: ([https://gallery.fitbit.com/details/5f75448f-413d-4ece-a53d-b969c6afea7c]).

I made this clockface for tracking my 2 type-1 sons. Currently I have an option in Sentinel One (the kid's version of the Sentinel clockfaces) to post heartrate values to nightscout through careportal at a user defined interval if over a user defined BPM. Right now I'm using the bg check eventType and putting the heartrate value in the glucose field.  Not ideal, and will definitely confuse school nurses.

If we could add a heartrate eventType to Careportal that used the same idea as a BG check eventType but just changed the label from glucose to HR, and maybe had a heart icon instead of a red dot, that would be great.  Any color dot that isn't red, gray, or orange (announcements) would work. Thanks.

**Comment by ryanchen26** [comment]
I think I'll just use the exercise event and put the HR in the notes.

**Comment by sulkaharo** [comment]
Hi! This is basically what the /activity API is for, only we never finished the implementation. I would not use Careportal for this. How are you planning to use the data?

**Comment by ryanchen26** [comment]
I would use the data to just look at the relationship between exercise intensity and blood glucose levels (in combination with IOB, and COB, time since last bolus, etc.). If there are clear patterns perhaps that information can be used to develop better dosing/snack/meal strategies before, during, after a particular exercise activity.

**Comment by PieterGit** [comment]
@ryanchen26 Can you have a look at the `activity` API implementation and see if you can make that work with Fitbit Sentinel clockfaces? See e.g. https://github.com/nightscout/cgm-remote-monitor/issues/3337 and https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/server/activity.js 

As far as I know only xdrip+ android app has limited support for uploading activity data.
Given the high frequency of heartrate info I agree with @sulkaharo and ould not want to add Heartrate as eventType option in the Careportal.
Please open a new PR for discussion about heartrate integration with Nightscout by generic logging activity data into Nightscout let's then extend the `activity` API for Nightscout (because that's more aimed for it than the careportal).

Agree that I close this issue?

**Comment by ryanchen26** [comment]
I'm not familair with the activity API for nightscout. I look forward to reading about it. In the meantime I'll just do my thing. Good luck.
