### ISSUE TITLE
Alexa API Internal Server Error

### ISSUE THREAD

**Issue by iybjc** [nightscout/cgm-remote-monitor#4906]
**Describe the bug**
Internal server error when sending NSStatus POST request to `https://(mydomain).herokuapp.com/api/v1/alexa`

**To Reproduce**
1. Use Fiddler or some other Web Debugger to debug responses etc.
2. Go to where you can manually send a request (in Fiddler it is Composer)
3. Send a POST Request with HTTP(S)1.1 to `https://(mydomain).herokuapp.com/api/v1/alexa`
4. Upload [this request body](https://pastebin.com/hBF3KMJS)
5. Execute the Request
6. Go to the request in Fiddler (marked with a 500 error)
7. Decode the Request Body and go to Web View to see the 500 error

**Expected behavior**
Server returns 500 error, indicating a problem perhaps related to [this issue](https://github.com/nightscout/cgm-remote-monitor/issues/4896)

**Screenshots**
![about_blank](https://user-images.githubusercontent.com/44852853/63398305-c5a3d200-c392-11e9-8aad-b62a9f3519a0.jpg)

**Your setup information**
- Nightscout 0.12.3
- Dexcom G6 w/ Share configured
- Non Specific

**Additional context**
Related to [this issue](https://github.com/nightscout/cgm-remote-monitor/issues/4896)
Going to `https://(mydomain).herokuapp.com/api/v1/alexa` gives `Cannot GET /api/v1/alexa` in any browser on multiple heroku instances, all with latest version of cgm-remote-monitor

**Comment by PieterGit** [comment]
@inventor96 Can you have a look at this issue?
@iybjc Please check https://github.com/nightscout/cgm-remote-monitor/pull/4980

**Comment by PieterGit** [comment]
Closing due to long inactivity. Please use new refactored 4980 Alexa PR if you still have problems with Alexa integration.

**Comment by inventor96** [comment]
@iybjc Going to the Alexa API URL in a browser will always give you an error because browsers make a `GET` request (unless web page code indicates otherwise) to URLs, and the Alexa API expects a `POST` request.

I made a request in the Alexa Developer Console to compare your request body to what they generate, and there was quite a bit more in what Amazon generated than what was in your example. Granted it was also simulating a device with a screen (as opposed to a device with just audio), but it's probably worth trying that out yourself to see if something is missing in your example.

Considering how much has changed with the virtual assistant stuff in #4980, please do the comparison as I described, and test it against the new code.
