### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by nathanscrivener** [nightscout/cgm-remote-monitor#4949]
In the readme, can we please update it under the section relating to BASE_URL. There should be a warning to users that if they set up auth roles, and need to set BASE_URL for API callbacks, they need to set this to include a token that has access.

**Comment by unsoluble** [comment]
Would be great if you could do a quick PR off `dev` for this; if the wording looks solid it should be a quick merge.

**Comment by jasoncalabrese** [comment]
@mtfoley, I saw your PR #5647 for this, but I'm not sure that the readme solution is the best way to handle this.

Instead of overloading `BASE_URL` so it includes the token, maybe it would be better have another way to mark a subject as default read, and then either use that token automatically, or send a redirect.

but I'm not sure what the use cases are for this

**Comment by mtfoley** [comment]
Don’t know enough about the various use cases to argue - I got the sense from the conversation above with @unsoluble and @nathanscrivener that it was just a README update that was needed. I could see how the BASE_URL could be spread a little thin if you used it for multiple external apps that didn’t require the same access though.

**Comment by mtfoley** [comment]
@jasoncalabrese @unsoluble would you guys rather I have a look at where the BASE_URL is used in the codebase and see which plugins might be using it?
