### ISSUE TITLE
Pump suspend/resume should be reflected in the basal pill and in the basal rendering for a consistent visual presentation of the current state.

### ISSUE THREAD

**Issue by jweismann** [nightscout/cgm-remote-monitor#5078]
**Describe the bug**
  
Whenever the pump is suspended then neither the Basal pill nor the basalrendering seem to be affected today (version 12.5).

Context:
We are using loop which correctly sends a pump suspend event to NS when the pump is being suspended. The pump suspend event is present in mongodb and the is also visualized with a grey dot in the cgm graph of NS.

One could argue that NS should only visualize the data that is present in mongodb and that the client is responsible for generating all the records relevant for a proper display of all pills and graphs. One could also argue that a pump suspend event is sufficient information that no insulin will be delivered before a pump resume will appear and hence NS is responsible for ensure a consistent visualization of the current state.

How do you see this ?

**To Reproduce**
Ensure that basal rendering is on and that the basal pill is present. Then generate a pump suspend event, verify that the event is present in mongodb, verify that NS notices it by drawing a grey pill on the cgm graph.

The consistency "bug"/"issue" can be seen by the fact that neither the basal pill changes nor the rendering of the current basal rate.

**Expected behavior**
If this isn't due to a (mis)-configuration then I would like to suggest that the Basal pill is set to the value 0.000 to reflect that no basal is being delivered when the pump is suspended. For the prefix, one could either stick to 'T:' or maybe used the letter s like 'S:' to make it more transparent that the delivery is 0.000 due to the pump being suspended.

The basal rendering should drop to zero too when the pump is being suspended.

**Your setup information**
Nightscout: 12.5
Loop: Dev

**Additional context**
Not sure how AndroidAPS and openAPS communicates pump suspend/resume events to NS
(are temporary basal events of 0 communicated too ?).

**Comment by inventor96** [comment]
I've brought up this idea in https://github.com/openaps/oref0/issues/1311 for OpenAPS. One thing to note is that there's not technically a "pump suspend event" in Nightscout; the grey dots are just generic notes created by the pump driver. From how I see it, we have two options:

1. Each pump driver (Loop, AAPS, OAPS) needs to send a temp 0 basal to NS when they recognize a suspend has occurred, and put the basal back to normal when a resume has occurred.
2. We need to create and handle "Pump Suspend" and "Pump Resume" events in Nightscout, and the pump drivers need to use those events instead of generic notes.

After your comments here, and thinking about the concept, I'm in favor of option 2, as option 1 could be tricky with temp basals that (right now) require a duration to be specified and could be re-calculated mid-suspend.

**Comment by jweismann** [comment]
I totally agree that from the NS perspective this should be regarded as feature request. I see the same options going forward and I also find option 2 to be the most appealing. I haven't looked at the code to see how big an effort that would take.
