### ISSUE TITLE
Performance optimisation needed

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#5130]
* in client/index.js, the dataExtent() function now takes 266ms to run on page load, which seems a performance regression in d3? This is called multiple times during the page load and seems the best optimisation for speeding the page rendering a _lot_.
* addBasals() in renderer.js takes 270ms to run on page load

**Comment by jpcunningh** [comment]
Thanks, @sulkaharo!

I have some ideas I can try later today to update the client so the dataExtent is only called once for each time the a data update is received from the server. That should help a lot. 

It does get called more than it used to due to changes in how the brush status is maintained in d3 v5.
