### ISSUE TITLE
Will Nightscout continue to work throughout the share server outages?

### ISSUE THREAD

**Issue by chernxbyl42069** [nightscout/cgm-remote-monitor#5260]
Not exactly a bug, but here goes. 

I haven’t used Nightscout for a while. It was a temporary solution for a smart watch. During the ongoing issues with Dexcom and their Share system outages, I decided to look back to Nightscout for a solution during this time. The graph on the Heroku-hosted website contains no data, but I thought data was read from a MongoDB generated directly from Dexcom. Should I even continue to pursue this, or will it not work, given the state of Dexcom’s Share/Follow system?

Specifics:
Dexcom G6 connected to Dexcom G6 app (iPhone), Nightscout hosted on Heroku, Nightscout app used on another iPhone

**Comment by whooze** [comment]
Well, the share-servers seems to be back online, at least that's what have been reported by some people.

To answer your question: No, with your current setup Nightscout gets the blood glucose data from Share-servers. That means that as long as share-servers are down - cgm-data is being sent to Nightscout.

There are ofcourse workarounds, like using Spike instead of the G6 app

**Comment by sulkaharo** [comment]
Nightscout is not strongly tied to Share servers and will stay up regardless of Dexcom servers, but the availability of data to Nightscout depends on how you've setup the data uploads. Sounds like you've setup the Dexcom Share Bridge in your Nightscout, which loads the data from Dexcom and thus won't have data available for as long as Dexcom servers are down. If you want to have the data available regardless of Dexcom server status, you need to use an uploader that sends the data directly to Nightscout, such as xDrip or Spike.
