### ISSUE TITLE
line-through/strikeout formatting not triggered on stale data

### ISSUE THREAD

**Issue by aaronjknox** [nightscout/cgm-remote-monitor#545]
Stale data isn't being formatted with strikethrough in dev branch
![image](https://cloud.githubusercontent.com/assets/7867106/6987205/113a6ba4-da02-11e4-99ef-f353f742d694.png)

**Comment by jimsiff** [comment]
@aaronjknox thanks for the report.  This should be fixed by @jasoncalabrese's commits to wip/focus-info.  This should be merged to dev soon.  https://github.com/nightscout/cgm-remote-monitor/pull/543

Closing for now.  Feel free to try wip/focus-info, or wait a couple days and update your copy of dev, then re-test.

**Comment by aaronjknox** [comment]
@jimsiff the focus-info branch did clear that up and shows the "# hrs ago" in the tab header. The numerous new features are great. Thanks!
