### ISSUE TITLE
Loop Pill data unavailable after 24 hours

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#5486]
**Describe the bug**
When scrubbing back in NS home screen graph, the Loop Pill shows no data and a warning symbol when you exceed 24 hours exactly from your current time. 

**To Reproduce**
1. Go to lower NS mini-graph
2. Click on graph and scroll back 24 hours and 1 minute or more
3. The loop pill will not show any data and have a warning symbol in place of the data.

**Expected behavior**
The Loop pill should remain intact, with its data and over data available like it does in the 23 hours since your current time.

**Screenshots**
24+ hours
![image](https://user-images.githubusercontent.com/46848705/73091533-7ad13d80-3e8f-11ea-8eed-4229e2643791.png)

Less than 24 hours
![image](https://user-images.githubusercontent.com/46848705/73091548-81f84b80-3e8f-11ea-9b6f-698642737d77.png)

**Your setup information**
- What version of Nightscout (e.g. 13.0.2-dev)
- What type of CGM, and how do you get your data there? ShareBridge
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No

**Additional context**
Running Loop Dev current as of 1/23/2020

**Comment by sulkaharo** [comment]
This is currently by design, where the amount of data needed by the client for loopers to render 48 hours of scroll back has been viewed as excessive in terms of data consumption (in some cases, this would mean the client loading >2MB of JSON when scrolling is started). It should be quite easy to make this configurable though, so I'll take a look at that.

**Comment by mtfoley** [comment]
@sulkaharo I sent a PR for this: #5651.
