### ISSUE TITLE
Treatments displayed on wrong place when no cgm data

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#630]
left enchilada right dev
![image](https://cloud.githubusercontent.com/assets/11146458/8125487/3f328062-10e6-11e5-8aad-f72bf90b31cb.png)
##

**Comment by stavlor** [comment]
Is left wip/push-notify or a different branch?

**Comment by jasoncalabrese** [comment]
I'm using a different method to find the position of a treatment that should help a lot with this, but doesn't seem to have worked for you.  Maybe something not right with unit conversions.

For treatments that don't have a BG, I'm now looking for the point before and the point after and taking the avg (no time limits, just 2 closest points).  In the past it took all the the point +/- 6m and averaged them.  Also now do this when the data is first received instead of each time the treatment is drawn.

**Comment by MilosKozak** [comment]
maybe because last point was only raw?

**Comment by jasoncalabrese** [comment]
I bet that's the issue, I need to make the filter a little better
https://github.com/nightscout/cgm-remote-monitor/blob/wip/push-notify/static/js/client.js#L1212

**Comment by jasoncalabrese** [comment]
Maybe https://github.com/nightscout/cgm-remote-monitor/commit/f90cf78cae4c68c9a014e3d60b64f8c5ce2d9bd9 will fix it

Really need to tear client.js apart so we can start adding tests
