### ISSUE TITLE
Integer values only for Nightscout report Target BG range bottom / top (using mmol/L)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6462]
Nightscout report Target BG range bottom / top using mmol/L:

Claims to require integer values for target range. Returns pink background in cell (error) for decimal values, but the graph and statistics accepts and displays target ranges with decimal values correctly (at least for BG range bottom, hard to tell if BG range top is rounded to integer values).

Additionally, even with English language, there is a Norwegian text explaining "Insert a valid value, the two nearest valid values are X and Y." This text is nowhere to be found in lib/language.js.

![image](https://user-images.githubusercontent.com/63544115/98946633-6a5c8300-24f4-11eb-80be-503ba354153c.png)

**Your setup information**
NS 14.0.7

**Comment by sulkaharo** [comment]
Right, the number validation here is based on the field being marked as a numeric and how this behaves thus depends on the browser. That hint text is a browser feature - which browser are you using? I changed the field to allow fractions which changed the behaviour in my end and fractions no longer produce the highlight, so this _should_ be fixed in next release.

**Comment by bjornoleh** [comment]
Ok, thanks. I have used Chrome on Windows 10.

**Comment by bjornoleh** [comment]
@sulkaharo Confirmed!
