### ISSUE TITLE
Intermittent full refresh on first load

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#6603]
Minor issue, but still worth investigation:

Site does a full refresh of itself within a second or two of initial load, but seemingly only on the first visit of the day (or hour, or some other timespan, haven't narrowed this down yet). Happens on macOS and iOS, current versions of each. Behaviour has been present since I believe 14.x.

**Comment by sulkaharo** [comment]
This is caused by the browser having flushed the cache for the web service worker and notifying the client it should update. Looks like this is a Safari bug, as according to the spec the browser should check if the file has changed content and only notify it's changed if the file contents are different. As such, not sure how to work around this
