### ISSUE TITLE
Treatments and other data show up with date of the next day

### ISSUE THREAD

**Issue by herzogmedia** [nightscout/cgm-remote-monitor#6773]
**Describe the bug**
Treatments and other data of the current day show in the reports as the following day. In fact every item shows as exactly one day in the future. On the other hand, administration tools don't find any treatment data in the future, so the database items seem to have correct timing and my xdrip+ readout also has correct timing.

**To Reproduce**
1. Add any data item (treatment, bg)
2. Open reports and find the item one day in th future

**Expected behavior**
Data added the current day show for the current day in the reports.

**Your setup information**
- 14.1.0
- Dexcom Bridge, Xdrip+ Receiver

**Comment by sulkaharo** [comment]
This sounds like the treatment profile in Nightscout and/or the computer you're viewing the data on has the wrong time zone.

**Comment by herzogmedia** [comment]
since the data is exactly 24 hours off that would only be possible if 1 viewed data with UTC +12 on a UTC -12 device, which I don't. Server runs on UTC and I am on UTC+1 (MET)

Found a clue however. This is the console output if I load todays treatments:

> got dataUpdate Date Tue Jan 19 2021 16:46:45 GMT+0100 (Mitteleuropäische Normalzeit)
> Adding 2021-01-18 for loading treatments reportclient.js:450:22
> Drawing  daytoday

So it actually does not load the current day but the day before

**Comment by haspden** [comment]
My thoughts were it would be in the date conversion potentially just on the graph display values. As you say the data seems correct, just the axis on the graph. I wondered if in the code it's adding x hours as days. I've only tested on GMT 1+ however. Could do with somebody going to GMT 2+ to test etc.

I'll see if I can see where the date/time axis are defined in the code and investigate at some point

**Comment by sulkaharo** [comment]
The reporting always loads multiple days of data to cover things like temp basal treatments that overlap multiple days. So far every report like this has been resolved by double-checking the time zone and date/time in the uploader device, treatment profile and the computer used to render the data is set correctly. Nightscout also has users across the world and the reporting is seems to be working as expected for practically everyone, and given there's no influx of reports the reporting is broken across the board, I think it's extremely unlikely you've found some obscure bug that only triggers for you. I can't reproduce this, so if you can PM me your Nightscout URL in Nightscout Discord, I can check if the issue is reproducible for me in your setup.

**Comment by haspden** [comment]
@sulkaharo  I will have to wait until I next travel to spain (post pandemic) to investigate, as when investigating I found that I only have the issue when actually being in a different country. Bizarrely, using VPN to spain and setting my TMZ to +1 doesn't allow me to reproduce the error on demand, and it's very possible the issue has been fixed in recent updates since I originally reported in #5025 18 months ago...

@herzogmedia  what NS version are you running ?

FWIW I'm on 
NS 14.1.0
and if you have good eyesight here are my config variables

![image](https://user-images.githubusercontent.com/4039041/107954776-cff95900-6f94-11eb-852d-97d174cb8594.png)

**Comment by herzogmedia** [comment]
My treatment profile switched to UTC for some reason. (Actually there were two sets of profiles with exactly the same name which is why I didn't see this before)
With the right timezone it now works as advertised. ;)
Thanks anyway!
