### ISSUE TITLE
Please change A1C estimation to GMI

### ISSUE THREAD

**Issue by Navid200** [nightscout/cgm-remote-monitor#6975]
**Is your feature request related to a problem? Please describe.**
This is a note from the Distribution Report page:
The formula used is taken from:Nathan, David M., et al. "Translating the A1C assay into estimated average glucose values." Diabetes care 31.8 (2008)

More research has been performed since 2008.  The formula has been updated.  Also, a new name has been adopted to reflect what it is.
Instead of estimated A1C, they have suggested we call it Glucose Management Indicator, or GMI.
https://care.diabetesjournals.org/content/diacare/41/11/2275.full.pdf

**Describe the solution you'd like**
I suggest we change the formula to the updated one and rename the parameter, in the table, to GMI.

**Describe alternatives you've considered**
We can stay with the old formula.  But, why?

I put together a comparison between the old and the updated formulas.  
![108939776-3bd86300-7620-11eb-9225-1e2c2dd80e8f](https://user-images.githubusercontent.com/51497406/112055073-c8e1df80-8b2c-11eb-853a-a237ba9725ef.png)

I searched and didn't find anything related.  Please close if this is a duplicate.
Thanks

**Comment by 4gra** [comment]
Hi, just adding my opinion - thanks for bringing GMI to my attention!

It makes sense to track the latest research, but in this case it doesn't make sense to throw the long-standing calculations out. Not all countries' healthcare systems will be using GMI (yet? at all?) and, besides, removing A1C makes it harder to compare with old results, so if the change were to be made, I'd suggest that including both would make sense for the forseeable future.

Aside: in the UK for example HbA1c still dominates, though notably also measuring in IFCC-standard mmol/mol rather than by percentage. It's not really clear from the abstract what confusion is likely to result from an 'estimate' being different to a measured value, and interpreting the 'new' results for most people would certainly require comparison to the 'old'.

**Comment by Navid200** [comment]
> Aside: in the UK for example HbA1c still dominates, 

Just to clarify, this is not about replacing the HbA1c test itself.  
This is about estimating it (the same Hb1A1c) using an updated formula.

**Comment by 4gra** [comment]
> > Aside: in the UK for example HbA1c still dominates,
> 
> Just to clarify, this is not about replacing the HbA1c test itself.
> This is about estimating it (the same HbA1c) using an updated formula.

Understood! Looks valuable. My point was mainly that replacing one with the other has implications for existing users. Also, I didn't think the notion of confusion - or reduction thereof - was well-evidenced, though admittedly I haven't read most of the citations.

**Comment by bewest** [comment]
We would consider pull requests for a new feature like this, unfortunately the few resources we have must go towards sustaining and fixing bugs.  Closing for now, although it sounds like a great idea for a contributor.
