### ISSUE TITLE
Compact Atlas collections from Admin Tools

### ISSUE THREAD

**Issue by goldendel** [nightscout/cgm-remote-monitor#7117]
**Is your feature request related to a problem? Please describe.**
The index on the entries collection is 10x the DB size after removing old entries.  Initially it shrunk a little, but after 2 weeks, it's still far bigger than the DB.

**Describe the solution you'd like**
Atlas has a [Compact](https://docs.mongodb.com/manual/reference/command/compact/) Method available via API.  It used to be possible to compact the DB via mlab.  There is no easy way to do this other than API having moved to Atlas.  It would be helpful to be able to shrink DB size after deleting DB documents via the NIghtscout Admin Tools.

**Describe alternatives you've considered**
I've tried installing MongoDB compass, but it's not clear how to issue the correct command to safely compact the collection.

**Additional context**
![image](https://user-images.githubusercontent.com/12022664/134889560-d5ad1ecd-4723-40b3-bd62-335c1633280f.png)

**Comment by thedewi** [comment]
Did you ever solve this? I've just spent more than 4 hours trying to understand this mess, and gotten nowhere. None of the examples I can find seem to be applicable to Atlas M0.

**Comment by goldendel** [comment]
Hi @thedewi.  Thanks for picking this up.  Not directl solution via this route.  To be quite honest, I'd forgotten I raised this, given it was back in September 2021.  With the move to paid plans at Heroku, I moved to a NightScout as a service provider (NightScout Pro).  There, the disk space is pretty much unlimited, so it's less of an impact.  Being able to compact the DB would be more space efficient, but I think there are likely higher value things you can work on.  I've dropped a note to Andy Low from NightScout Pro to see if he has strong opinions on this.  If not, I'm happy to close the issue/feature request.

**Comment by thedewi** [comment]
Thanks. I'm not sure a _nice_ solution is possible on the Mongo Atlas free tier, but I did it the slow disruptive way - told Nightscout to delete old records, did a full `mongodump`, terminated the whole cluster, and did a full `mongorestore` onto a new one. The restore part takes an hour or more; I guess rebuilding every index with minimal CPU time is a big job. But ultimately it coped better than Northflank's free tier, which actually runs out of memory if you try to rebuild big indexes.

**Comment by goldendel** [comment]
Closed as more compact DB size is less of an issue with NSaaS.  Given the dev community have not picked this up in almost 3 years they clearly have other priorities for Nightscout.

**Comment by simgislab** [comment]
Here is my solution for Atlas M0 (I run my NS instance on Railway). I'm running it since 2019, so there was a lot of clutter. Finally my DB reached quota and AAPS stopped worked queuing all the uploads.

Deleting old Nightscout records (keeping 3 last years) via GUI did not reduce the reported database size enough, on opposite it grew even more to 115-117% and eventually Atlas blocked writes because the 512 MB quota was exceeded.

After investigating with db.stats() and db.entries.stats(), I found that the actual problem was mostly the indexes, not the data itself.

Before rebuilding the indexes:

* dataSize: ~242 MiB
* indexSize: ~311 MiB
* total logical size: ~553 MiB
* entries indexes alone: ~295 MiB

I rebuilt the entries indexes one by one (dropping and immediately recreating each with the same definition). Some of them were dramatically smaller after rebuilding. For example:

* sgv_1: ~23 MiB → ~3 MiB
* type_1: ~18 MiB → ~2 MiB
* dateString_1: ~37 MiB → ~11 MiB
* identifier_1: ~17 MiB → ~2 MiB
* srvModified_1: ~17 MiB → ~2 MiB

After rebuilding all required indexes, the database is now:

* dataSize: ~244 MiB (AAPS poured queue over)
* indexSize: ~108 MiB
* total logical size: ~352 MiB
* same 56 indexes as before

So roughly 200 MiB was recovered just by rebuilding indexes, without deleting additional Nightscout history.

One important warning: on Atlas M0, rebuilding an index while already over quota can fail because createIndex() is considered a write. I had to temporarily drop enough indexes to get below the quota/write-block threshold before recreating them.

This suggests that after large amounts of old data are deleted/pruned, the Atlas quota can remain exhausted because the existing indexes retain a lot of space. Rebuilding the indexes can reclaim a very significant amount of that space.

I used mongosh.
