### ISSUE TITLE
Intermittent NS COB display of 0 g

### ISSUE THREAD

**Issue by marionbarker** [nightscout/cgm-remote-monitor#7765]
**Describe the bug**
The NS COB pill sometimes goes to 0 g between updates from Loop
* Previous upload, e.g., 10 g, is displayed in NS COB pill following upload from Loop
* When upload from Loop is more than 6 minutes old, NS COB Pill sometimes displays 0 g until the next Loop upload arrives
* Next upload, e.g., 20 g, is displayed in NS COB pill following upload from Loop

I am capturing this for a particular test case that demonstrated this odd behavior.
Out of 9 tests today, observed this 4 times.
We examined the devicestatus.json (attached below) and there were no uploads from Loop that would have stimulated the NS COB to indicate 0 g. 
In fact the Loop Pill still shows COB from last upload as shown in the screen shot below.
This appears to be timing related in NS.

I will be happy to perform additional tests if desired.

**To Reproduce**
1. Use Loop-dev on a test phone that is fed by Dexcom Share as the CGM source using an rPi DASH simulator for a pump
2. Upload from Loop-dev to Nightscout site
3. Use Dexcom Share to supply the CGM data to that Nightscout site
4. Use a different phone to test a new LoopCaregiver (LCG) app that sends remote commands to a Looper's phone
5. When NS site says 3 or 4 minutes since last Loop, issue the remote command from LCG phone (use 10 g to make it easy to see)
6. The remote carb entries are all promptly received at the Loop Phone and within 10 sec the plot updates showing the entry
7. For last test, interrupted the rPi simulator, which paused the uploads to NS. The NS COB pill remained 0 until rPi pod simulator was resumed about 5 minutes later. This caused a new upload from Loop and all pills updated as expected.

**Expected behavior**
Expect the NS COB pill to remain unchanged until the next Loop upload

**Screenshots**

![Screenshot 2022-12-06 at 4 05 11 PM](https://user-images.githubusercontent.com/19607791/206054627-3d766f1f-31a3-4511-9982-03cbe1d8d207.png)

**Attached json file that corresponds to screen shot**

Note - local time is PST or 8 hours earlier than GMT.
[NS_COB_Issue_Run2_devicestatus.json.zip](https://github.com/nightscout/cgm-remote-monitor/files/10171787/NS_COB_Issue_Run2_devicestatus.json.zip)

**Your setup information**
- What version of Nightscout 12.4.6
- What type of CGM, and how do you get your data there? ShareBridge
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? only tested on Chrome

**Additional context**
Other configuration parameters:
Configuration for NS:
* Using Dexcom Bridge for CGM; version 14.2.6 built using Google Cloud, site is readable (at current time)

Configuration LoopCaregiver Phone:
* commit 5b8aad9 Localize carb and bolus view numbers

Configuration Loop Phone:
The LoopWorkspace commit is: 9fd16c2
With patch applied for remote information uploading while Loop phone is locked
* from gestrich: branch bugfix/2022-12/bg/ns-delayed-uploads (Loop PR 1857)

**Comment by bewest** [comment]
Thanks, @marionbarker.  It's likely this issue is related to the cob plugin module:
https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/plugins/cob.js#L80-L96

A simple check would be to change the reference from `times.mins(5)` to `times.mins(15)` or perhaps a reference to some constant at the top defined as `MIN_DEVICESTATUS_SAMPLE_INTERVAL` or similar.

**Comment by bewest** [comment]
Looks like intent of that code, as-is will look for any device status entries from five minutes in the future including 30 minutes in the past.

**Comment by sulkaharo** [comment]
I recall the original discussion here was, we need to have some threshold for how old data is displayed from external algorithms. In case of COB, showing a non-decayed COB for too long can lead to user assuming the COB is correct and bolusing based on the data, so it's safer to drop to 0 if the data is deemed too old. I agree we could show data that's older than 5 minutes, but probably not _much_ older data. OpenAPS uploads a devicestatus with COB on every 5 minutes and doesn't exhibit this issue as a result.

**Comment by marionbarker** [comment]
I will modify a fork as Ben suggested and test it. Thanks much. 

Loop uploads at 5 minute intervals but sometimes there’s a reason why it misses a cycle. This test case is odd because there is no heartbeat and both NS and Loop are fed by Dexcom Share, which causes the Loop cycle to drift later than 5 minutes.

Once I’ve confirmed this fixes it, we can decide about Sulka’s concern for what the time ahead should be before I submit a PR.

**Comment by sulkaharo** [comment]
The relevant line for this issue is https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/plugins/cob.js#L48 that ignores the COB from device statuses if the latest status upload is over 10 minutes old. The line Ben was pointing to has a threshold that allows the uploaded COB timer to be up to 5 minutes in the future. I'd say 10 minutes starts to be about where my comfort level lies at for the data, especially if we allow the uploads to be up to 5 minutes wrong, which effectively means the data shown in NS UI is up to 15 minutes old.

**Comment by marionbarker** [comment]
Given that Sulka is not comfortable making changes and I believe Loop is contributing to the issue, I'll close this.

Thank you for your assistance.

I switched to timing tests using direct carb entry on Looper's phone, instead of remote carbs, to remove one more variable.
The timing for COB going to 0 was (for 3 successive tests):
* Loop ago = 7 minutes
* Loop ago = 6 minutes
* Loop ago = 7 minutes

I believe we are seeing Loop ago < 10 minutes for the NS COB going to zero is because:
* the Looper's phone updates carbs and carbs show on the plot for NS promptly
* the Loop Pill (and NS COB) do not update until the next Loop cycle
* when I start the timing after the COB updates on NS, I've already used up part of the 10 minutes

I'll head back to the Loop developers with this information.

**Comment by bewest** [comment]
@marionbarker, I think we can keep this open and have a reasonable discussion about design intent, and if there is room for enhancements.  I don't see Sulka shutting things down here, but helpful in providing perspective.
Carbs tend to work on a slower timeline than glucose: after 10 minutes, you basically have the same carbs on board.  For carbs in particular, these values don't change much before 30 minutes, so conceivably even values of 45 minutes old could be more useful than reporting 0.  Given Sulka's reticence, I won't push for that long, though.
I think it would make sense to choose a value between 10 and 15 minutes, so that if Loop is able to sync up exactly on the 5 minute cadence there is room for some jitter.
