### ISSUE TITLE
nightscout/cgm-remote-monitor:latest Docker image still deploys 14.2.6

### ISSUE THREAD

**Issue by psonnera** [nightscout/cgm-remote-monitor#8171]
**Describe the bug**
Deploying the Docker image https://hub.docker.com/layers/nightscout/cgm-remote-monitor/latest/images/sha256-66773162fda8380f43981efcd472de334444df2645364f173e77e2a956b856f1?context=explore results in 14.2.6 instead of 15.0.2

**To Reproduce**
docker compose down
change the yml to nightscout/cgm-remote-monitor:latest
docker compose up and check version: it's 14.2.6

**Expected behavior**
docker compose down
change the yml to nightscout/cgm-remote-monitor:latest_dev
docker compose up and check version: it's 15.0.0 (or .2) as per https://github.com/nightscout/cgm-remote-monitor/releases

**Screenshots**

**Your setup information**
https://github.com/psonnera/NSDockVPS

**Additional context**

**Comment by psonnera** [comment]
Wow, thanks @ireneusz-ptak that was it. I was convinced up would pull it automatically. Probably I should `docker compose up -d --force-recreate`. Funnily enough changing container from latest to latest_dev does pull but somehow when returning to latest it doesn't.
Issue closed. User mistake.

**Comment by ireneusz-ptak** [comment]
That's why the preferred option is to use version numbers instead of latest.
If you've already downloaded latest locally it will be reused till you pull it again (you don't want the version to be upgraded between runs). In your case you didn't use latest_dev previously, so it had to be downloaded. Simple as that.
