### ISSUE TITLE
Pushover / split treatments and alarms as separate streams

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#906]
After seeing responses from people using Pushover with Funnel Cake -- which now sends all site alerts through Pushover, as well as treatments -- it seems that it would be nice to have an option to split it out so that you could get any of these by setting a separate variable:

-- alerts
-- treatments
-- all events (alerts, treatments, and announcements)
-- announcements (which is a new feature with its own variable)

Since "announcements" has been set up to be a separate stream, it seems possible to have treatments be separate from alerts. Some users only want treatment pushovers.

.

**Comment by GrantKY** [comment]
Would definitely agree with Amy.  The ability to select which alerts are sent to pushover and perhaps even the acknowledgement period based on alarm type would be a definite enhancement.

**Comment by jasoncalabrese** [comment]
I'm thinking about doing this using the same ns-* events that we use for maker

Lots more discussion over at: https://www.facebook.com/groups/cgminthecloud/permalink/812280718893186/

**Comment by jasoncalabrese** [comment]
While not exactly what was asked for I think #933 will cover most of the issue people have with push over and even adds a new feature. It works by repurposing some existing config options and adding a couple some more.

To disable high alarms system wide (can be re-enabled per browser client) use `ALARM_HIGH="off"`

Pushover will use the first value in the `*_MINS` settings, so to make the snooze time for highs longer, do something like this: `ALARM_HIGH_MINS="60 90 120"`

With this we get a new feature where you can select the options used for each alarm event type, shorted time for lows, longer times for highs, etc.

**Comment by jasoncalabrese** [comment]
After discussing with @StuArnold on :point_up: [gitter](https://gitter.im/nightscout/public?at=55eaa8440b6aa72b12ffd914) we decided that we really needed to add `PUSHOVER_ANNOUNCEMENT_KEY`, the keys work like this (from the readme).

* `PUSHOVER_USER_KEY` - Your Pushover user key, can be found in the top left of the [Pushover](https://pushover.net/) site, this can also be a pushover delivery group key to send to a group rather than just a single user.  This also supports a space delimited list of keys.  To disable `INFO` level pushes set this to `off`.
* `PUSHOVER_ALARM_KEY` - An optional Pushover user/group key, will be used for system wide alarms (level > `WARN`).  If not defined this will fallback to `PUSHOVER_USER_KEY`.  A possible use for this is sending important messages and alarms to a CWD that you don't want to send all notification too.  This also support a space delimited list of keys.  To disable Alarm pushes set this to `off`.
* `PUSHOVER_ANNOUNCEMENT_KEY` - An optional Pushover user/group key, will be used for system wide user generated announcements.  If not defined this will fallback to `PUSHOVER_USER_KEY` or `PUSHOVER_ALARM_KEY`.  A possible use for this is sending important messages and alarms to a CWD that you don't want to send all notification too.  This also support a space delimited list of keys. To disable Announcement pushes set this to `off`.
